Planck rev6 drop
vial-kb/vial-qmk pull request #105
Opened 2022-01-18 11:25 UTC by dijidiji

- Added Vial support for the Drop Planck rev6 including VialRGB lighting
- Enabled QMK RGB matrix to allow for the aforementioned VialRGB to work

Presumably this works for all Planck variants but I'm unable to test anything other than the Drop rev6.

2022-01-18 16:57 UTC, xyzz requested changes
If you've only tested the keymap with `rev6_drop`, then the keymap should go under the `rev6_drop` folder.

2022-01-18 16:57 UTC, xyzz commented on keyboards/planck/keymaps/vial/olkb-planck-rev6.1.json:Zone.Identifier
> +[ZoneTransfer]
Shouldn't be in the PR

2022-01-19 02:12 UTC, dijidiji commented on keyboards/planck/keymaps/vial/olkb-planck-rev6.1.json:Zone.Identifier
> +[ZoneTransfer]
Oops, seems to have snuck in.

2022-01-19 02:14 UTC, dijidiji commented
> If you've only tested the keymap with `rev6_drop`, then the keymap should go under the `rev6_drop` folder.

vial keymap folder moved under `rev6_drop`, to be honest I had no idea keymaps could be that specific but it compiles and functions as expected!

2022-01-19 04:31 UTC, merged