Added Johan von Konow 3DPCB Keyboard
vial-kb/vial-qmk pull request #209
Opened 2022-07-24 02:55 UTC by jkutianski

Added port of Johan von Konow 3DPCB Keyboard to VIAL

- Support RX/TX leds as NumLock & CapsLock
- Support blink RX/TX leds for layer indication
- Change MO(0) & MO(1) to FN_MO13 & FN_MO23

2022-07-24 03:52 UTC, xyzz requested changes

2022-07-24 03:52 UTC, xyzz commented on keyboards/handwired/3dpcb/config.h
> +#define VIAL_UNLOCK_COMBO_COLS {0,5};
Vial-specific options should go under the vial keymap

2022-07-24 03:52 UTC, xyzz commented on keyboards/handwired/3dpcb/rules.mk
> +KEY_OVERRIDE_ENABLE = 	no
Same as above about vial-specific options

2022-07-24 05:42 UTC, merged

2023-03-28 21:46 UTC, lesshonor commented
This `vial` keymap doesn't actually have a `vial.json`.

This entire keyboard is probably in danger of removal because not only has the `vial` keymap been broken for close to a year, the rest of the keyboard no longer compiles [when the latest changes from QMK are incorporated](https://github.com/vial-kb/vial-qmk/tree/merge-2023-03-12).

Consider opening up a new PR to fix the `vial` keymap and [migrate the necessary information to `info.json`](https://docs.qmk.fm/#/ChangeLog/20221126?id=usb-ids-refactoring).