Add mini49 to keyboards
vial-kb/vial-qmk pull request #381
Opened 2023-02-25 02:48 UTC by pcs3rd

- [x] VIAL_INSECURE is not set
- [x] Vial layout is at keyboards/mini49/via

2023-02-27 04:10 UTC, lesshonor requested changes
Additionally, delete the STLs from this pull request. Vial-QMK is a repository for firmware, not 3D models.

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/config.h
> +
This entire file isn't necessary in its current form. 0,0 is the default for bootmagic lite, and the chance of that ever changing as long as the feature exists is basically zero.
```suggestion
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/default/keymap.c
> +    [0] = LAYOUT_mini49(
```suggestion
    [0] = LAYOUT(
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/info.json
> +            "LAYOUT_mini49": {
```suggestion
            "LAYOUT": {
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/via/config.h
> +
1. Compiling VIA keymaps is not supported with the `vial-qmk` repo.
2. Only lines 10 and 11 might potentially be useful in a VIA keymap.
3. You already have a `vial` keymap folder. There is no need to create an exact duplicate of it in a folder named `via`.

Ultimately my suggestion is to delete the entire `via` folder. If you want a VIA keymap, submit your keyboard to [the QMK repository](https://github.com/qmk/qmk_firmware). (Many of the suggestions I am making would be requirements for acceptance there.)

```suggestion
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/vial/keymap.c
> +    [0] = LAYOUT_mini49(
```suggestion
    [0] = LAYOUT(
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/rules.mk
> +#EXTRAKEY_ENABLE = #Don't need this?
1. MCU and bootloader were already defined in `info.json`.
2. None of the rest is necessary.
3. Comment says `# This file intentionally left blank`...but it isn't.
```suggestion
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/vial/config.h
> +#define VIAL_UNLOCK_COMBO_COLS {0}
Per [the docs](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination):
> You should configure a combo of at least 2 keys

This may not be a strict requirement for boards with more than one key. I'd still adhere to it.
```suggestion
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 9}
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/mini49.h
> +    {K40, K41, K42, K43, ___, K45, K46, K47, K48, K49}  \
You should look into migrating this information to `info.json`. (`qmk info -f json -kb mini49` may help.)

This is not currently a strict requirement for Vial submissions. If Vial continues to bring in changes from upstream QMK it will likely become one, and if that happens your board will break.
```suggestion
#define LAYOUT( \
    K00, K01, K02, K03, K04, K05, K06, K07, K08, K09, \
    K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, \
    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, \
    K30, K31, K32, K33, K34, K35, K36, K37, K38, K39, \
    K40, K41, K42, K43,    K45,   K46, K47, K48, K49 \
) \
{ \
    {K00, K01, K02, K03, K04, K05, K06, K07, K08, K09}, \
    {K10, K11, K12, K13, K14, K15, K16, K17, K18, K19}, \
    {K20, K21, K22, K23, K24, K25, K26, K27, K28, K29}, \
    {K30, K31, K32, K33, K34, K35, K36, K37, K38, K39}, \
    {K40, K41, K42, K43, ___, K45, K46, K47, K48, K49}  \
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/readme.md
> +- Physical reset button: Briefly press the button on the RP2040
```suggestion
- Physical reset: Hold the BOOT button down while pressing the RESET button.
```
...Gonna guess just pressing the RESET button once doesn't actually expose the RPI-RP2 volume for flashing.

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/mini49.h
> +#pragma once
```suggestion
/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/vial/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
/* SPDX-License-Identifier: GPL-2.0-or-later */
#include QMK_KEYBOARD_H
```

2023-02-27 04:10 UTC, lesshonor commented on keyboards/mini49/keymaps/default/keymap.c
> +#include QMK_KEYBOARD_H
```suggestion
/* SPDX-License-Identifier: GPL-2.0-or-later */
#include QMK_KEYBOARD_H
```

2023-02-27 11:05 UTC, lesshonor requested changes

2023-02-27 11:05 UTC, lesshonor commented on keyboards/mini49/keymaps/default/keymap.c
> +     */
```suggestion
```
A diagram like this isn't very useful since it doesn't match the board's physical layout and just has filler data. Consider fixing it or deletimg it.

2023-02-27 11:05 UTC, lesshonor commented on keyboards/mini49/keymaps/vial/keymap.c
> +     */
```suggestion
```
As noted above.

2023-02-27 11:05 UTC, lesshonor commented on keyboards/mini49/readme.md
> +![mini49](https://raw.githubusercontent.com/pcs3rd/qmk_firmware/master/keyboards/mini49/resources/keeb.jpg)
Github isn't really an image host, and this isn't a permanent link.  If you were to begin following the [git guidelines in the QMK documentation](https://docs.qmk.fm/#/newbs_git_best_practices), it would break.

I would have suggested a permanent link but the original image is also too big. Consider Imgur or another image hosting service and a maximum size of 1024x1024px ("huge thumbnail").

2023-03-21 03:40 UTC, pcs3rd commented on keyboards/mini49/rules.mk
> +#EXTRAKEY_ENABLE = #Don't need this?
Excluding `ALLOW_WARNINGS = yes` results in a compilation failure at `lib/pico-sdk/src/rp2_common/hardware_flash/flash.c`

2023-03-21 03:46 UTC, pcs3rd commented on keyboards/mini49/config.h
> +
Removed this file.

2023-03-21 03:47 UTC, pcs3rd commented on keyboards/mini49/keymaps/default/keymap.c
> +    [0] = LAYOUT_mini49(
Added suggested change.

2023-03-21 03:49 UTC, pcs3rd commented on keyboards/mini49/info.json
> +            "LAYOUT_mini49": {
Added suggested change.

2023-03-21 03:50 UTC, pcs3rd commented on keyboards/mini49/keymaps/via/config.h
> +
Removed via keymap

2023-03-21 03:54 UTC, pcs3rd commented on keyboards/mini49/keymaps/vial/config.h
> +#define VIAL_UNLOCK_COMBO_COLS {0}
Added suggested.

2023-03-21 03:55 UTC, pcs3rd commented on keyboards/mini49/readme.md
> +- Physical reset button: Briefly press the button on the RP2040
Updated readme with suggested.

2023-03-21 03:56 UTC, pcs3rd commented on keyboards/mini49/mini49.h
> +#pragma once
Added.

2023-03-21 03:56 UTC, pcs3rd commented on keyboards/mini49/keymaps/default/keymap.c
> +     */
Removed.

2023-03-21 04:07 UTC, pcs3rd commented on keyboards/mini49/mini49.h
> +    {K40, K41, K42, K43, ___, K45, K46, K47, K48, K49}  \
I'll check this out.

2023-03-21 04:08 UTC, pcs3rd commented on keyboards/mini49/readme.md
> +![mini49](https://raw.githubusercontent.com/pcs3rd/qmk_firmware/master/keyboards/mini49/resources/keeb.jpg)
I've moved this out of the branch, along with the stl's mentioned earlier.    
I'll update the image this week.

2023-03-22 22:53 UTC, lesshonor commented on keyboards/mini49/rules.mk
> +#EXTRAKEY_ENABLE = #Don't need this?
> Excluding `ALLOW_WARNINGS = yes` results in a compilation failure at `lib/pico-sdk/src/rp2_common/hardware_flash/flash.c`.

What's your `qmk doctor` say? I can't replicate this failure using arm-gcc 8.3.1, 10.3.1, or 12.2.0 with the requisite pico-sdk update (see #322)

2023-03-22 22:57 UTC, lesshonor requested changes

2023-03-22 22:57 UTC, lesshonor commented on keyboards/mini49/info.json
> +            "filename": "keyboards/mini49/mini49.h",
```suggestion
```

2023-03-22 22:57 UTC, lesshonor commented on keyboards/mini49/mini49.h
> +/* SPDX-License-Identifier: GPL-2.0-or-later */
This file can be deleted since your layout is in `info.json` now.

2023-03-24 15:37 UTC, pcs3rd commented on keyboards/mini49/rules.mk
> +#EXTRAKEY_ENABLE = #Don't need this?
That resolved it.

2023-03-24 18:56 UTC, lesshonor commented on lib/pico-sdk
The code changes are perfect, but...you're gonna want to revert the submodule change, and be more careful about what you include in your commits in the future. (`git add keyboards`, not `git add .`, and run `git status` to verify what you're including before you commit.)

This change is only necessary on your own setup -- QMK wasn't officially targeting arm-gcc 12.2.x at 18.5.x -- and the upcoming merge from QMK upstream doesn't use this commit for `pico-sdk`.

2023-04-12 19:41 UTC, pcs3rd commented on lib/pico-sdk
pico-sdk has been reverted back to 07edde8e49890d2172bbc272aacc119f999df063.

2023-04-12 23:14 UTC, lesshonor approved these changes

2023-04-16 04:22 UTC, merged