Port Arc60h hotswap PCB
vial-kb/vial-qmk pull request #386
Opened 2023-03-01 19:32 UTC by stanrc85

Port for Arc60h hotswap PCB, this version uses a unique json compared to the solder version.

2023-03-03 03:49 UTC, lesshonor requested changes
...This one you might want to mark as draft until the rest of the keyboard makes it into Vial. Since it was added to upstream QMK less than a month ago, that might be a while.

2023-03-03 03:49 UTC, lesshonor commented on keyboards/vertex/arc60h/keymaps/vial/keymap.c
> +}*/
```suggestion
```
Always turn off RGB when the keyboard starts? Don't think most people would want that.

2023-03-03 03:49 UTC, lesshonor commented on keyboards/vertex/arc60h/keymaps/vial/rules.mk
> +KEY_OVERRIDE_ENABLE = no
```suggestion
```
Do you really need to disable these?

2023-03-03 03:49 UTC, lesshonor commented on keyboards/vertex/arc60h/keymaps/vial/vial.json
> +      "Backspace",
```suggestion
      "Split Backspace",
```

2023-03-03 03:49 UTC, lesshonor commented on keyboards/vertex/arc60h/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
```suggestion
```
This is the default, so you don't really need to mention it.

2023-03-03 10:33 UTC, stanrc85 commented on keyboards/vertex/arc60h/keymaps/vial/keymap.c
> +}*/
I was building this for users on the Arc60 discord, I had intended to remove it sorry about that.

2023-03-03 10:34 UTC, stanrc85 commented
all changes have been addressed.  I'll mark as draft for now until the changes from QMK are merged.  Thanks

2023-07-17 11:15 UTC, stanrc85 commented
This should be ready for review and merge now that the PCB is added from latest QMK merge.

2023-07-17 16:25 UTC, merged