Add Vial support for Keebio Sinc revs 1-3
vial-kb/vial-qmk pull request #404
Opened 2023-03-10 13:21 UTC by kevinmost

Based this off the initial QMK commit that added rev 3 support: https://github.com/qmk/qmk_firmware/tree/42c240f6cfe697744cdf876ace1e7273f43db60d/keyboards/keebio/sinc

Later snapshots of that directory would not work with Vial due to breaking changes in QMK that have not been merged.

Disabled quite a few features in revs 1 and 2 due to size constraints. However, rev 3 uses a RP2040 with much more flash memory, so nothing had to be disabled there.

Tested:
  - `make keebio/sinc/rev1:vial`, `make keebio/sinc/rev2:vial`, and `make keebio/sinc/rev3:vial` all compile successfully
  - Flashed the rev3 firmware to my Sinc rev3 and am able to use Vial

2023-03-14 07:05 UTC, xyzz requested changes
> Disabled quite a few features in revs 1 and 2 due to size constraints

these changes should go into the vial keymap, not into the revision. you can make a new keymap under e.g. keyboards/keebio/sinc/rev1/keymaps/vial - these all should also have different VIAL_KEYBOARD_UID since it's different pcb

2023-03-18 13:41 UTC, kevinmost commented
@xyzz Thanks for the review, that makes sense. I updated the PR.

2 questions:

1) I had to put the `#define DYNAMIC_KEYMAP_LAYER_COUNT 0` definitions into `rev1/config.h` and `rev2/config.h`. Trying to put them in `rev1/keymaps/vial/config.h`, for example, resulted in the following error. Is this right?

```
./keyboards/keebio/sinc/rev2/keymaps/vial/config.h:28:0: error: "DYNAMIC_KEYMAP_LAYER_COUNT" redefined [-Werror]
 #define DYNAMIC_KEYMAP_LAYER_COUNT 1
 ^
In file included from <command-line>:0:0:
./.build/obj_keebio_sinc_rev2/src/info_config.h:45:0: note: this is the location of the previous definition
 #   define DYNAMIC_KEYMAP_LAYER_COUNT 3
 ^
```

2) Is a Vial firmware compiled with `DYNAMIC_KEYMAP_LAYER_COUNT` set to 0 actually functional, or does it mean that you don't even get a base layer to map? I did everything else to [reduce firmware size](https://get.vial.today/docs/firmware-size.html) and couldn't make the firmware fit. Even setting the layer count to 1 is not enough.

If this is non-functional, then should I just remove the rev1/rev2 directories and have this PR just add rev3 support?

2023-03-18 14:55 UTC, lesshonor commented
>     1. I had to put the `#define DYNAMIC_KEYMAP_LAYER_COUNT 0` definitions into `rev1/config.h` and `rev2/config.h`. Trying to put them in `rev1/keymaps/vial/config.h`, for example, resulted in the following error. Is this right?
> ```
> ./keyboards/keebio/sinc/rev2/keymaps/vial/config.h:28:0: error: "DYNAMIC_KEYMAP_LAYER_COUNT" redefined [-Werror]
>  #define DYNAMIC_KEYMAP_LAYER_COUNT 1
>  ^
> In file included from <command-line>:0:0:
> ./.build/obj_keebio_sinc_rev2/src/info_config.h:45:0: note: this is the location of the previous definition
>  #   define DYNAMIC_KEYMAP_LAYER_COUNT 3
>  ^
> ```

If you're redefining a preprocessor macro, you have to `#undef` it first.

e.g.:
https://github.com/vial-kb/vial-qmk/blob/47721416a6483a1d759c21a18beae3c0cb7d3eb2/keyboards/binepad/bnr1/keymaps/vial/config.h#L14-L17

2023-03-18 14:58 UTC, kevinmost commented
That worked, thanks!

2023-03-18 19:05 UTC, lesshonor requested changes

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/info.json
> +    "features": {
Please revert all changes to the keyboard-level files. Per xyz it's not so bad if the changes match QMK but some of these definitely don't (upstream still has `sinc/rev1/config.h`)

You're welcome to do this in your own copy of the repository, but incorporating these changes now will make merging changes from upstream QMK more of a pain than it already is.

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/keymaps/via/keymap.c
>      _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______, _______, _______
Please revert. Compiling VIA keymaps is not supported in the Vial repository (don't take my word for it; try running `make keebio/sinc:via` for yourself) so there is no need to modify anything about the `via` keymap.

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/rev1/keymaps/vial/config.h
> +#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
Do you know that this works the way you expect? VIA ≠ Vial.

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/rev1/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 0
```suggestion
```
> Is a Vial firmware compiled with DYNAMIC_KEYMAP_LAYER_COUNT set to 0 actually functional, or does it mean that you don't even get a base layer to map?

...You should understand the effects a setting will have before inflicting it on other people. Aside from doing something like flashing a test Pro Micro, you can most definitely flash your rev3 with this `#define` set, and see if you like the results.

By the way, [there are many other things that can be done to control size on AVR besides reducing the number of layers](https://docs.qmk.fm/#/squeezing_avr). Removing most RGB animations is very common. No one has mechanical locking keys either:

https://github.com/vial-kb/vial-qmk/blob/47721416a6483a1d759c21a18beae3c0cb7d3eb2/keyboards/mechwild/murphpad/keymaps/vial/config.h#L17-L39

Ultimately, if you don't want to go the extra mile it's fine if you just submit for rev3.

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/rev3/keymaps/vial/vial.json
> +  "menus": ["qmk_rgb_matrix"],
```suggestion
  "lighting": "vialrgb",
```
VIA ≠ Vial. Please reference [the Vial lighting documentation](https://get.vial.today/docs/lighting.html#rgb-matrix--vialrgb).

2023-03-18 19:05 UTC, lesshonor commented on keyboards/keebio/sinc/rev3/keymaps/vial/rules.mk
> +ENCODER_MAP_ENABLE = yes
```suggestion
ENCODER_MAP_ENABLE = yes

VIALRGB_ENABLE = yes
```
If you've got RGB_MATRIX and plenty of RAM, you might as well leverage Vial's UI.

2023-03-19 17:11 UTC, kevinmost commented
Thanks for the review. I've done the following:

- Pulled in the latest [upstream](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keebio/sinc) `sinc` directory as a base (which adds rev3 support)
- Ensured my edits on top of that are only in the new `keymaps/vial` directories for each rev

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/info.json
> +    "features": {
The [current `vial-qmk`](https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/keebio/sinc) main branch doesn't have the most recent `rev3` changes that are in the [upstream](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keebio/sinc).

So I pulled in the current QMK upstream for the whole `keyboards/keebio/sinc` directory, and then added the `{rev1|rev2|rev3}/keymaps/vial` directories.

(Note: I did not merge in the `keymaps/` directory from upstream, but could do that too)

LMK if you would prefer that I do something else here, but this seems to make merging from upstream cleaner in the future, IMO, as the diff vs upstream is strictly new files now.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/keymaps/via/keymap.c
>      _______, _______, _______, _______, _______, _______, _______, _______,          _______, _______, _______, _______, _______, _______, _______, _______
Reverted.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/rev1/keymaps/vial/config.h
> +#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
Reverted.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/rev1/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 0
Thanks for that link, that helps.

I was able to get rev1 and rev2 to compile by disabling:

- Locking keys
- Space Cadet
- Grave Escape

And I removed the changes to `DYNAMIC_KEYMAP_LAYER_COUNT`.

I do not have a Pro Micro to test on, unfortunately.

Would you prefer I revert any changes to the rev1 and rev2 directories? I can do that, or add some note about how this was not tested on a board.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/rev1/keymaps/vial/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 0
Side-note: Is it possible to add a link to that "Squeezing AVR" page to https://github.com/vial-kb/vial-kb.github.io/blob/main/docs/docs/firmware-size.md? I can send a PR.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/rev3/keymaps/vial/vial.json
> +  "menus": ["qmk_rgb_matrix"],
Done.

2023-03-19 17:12 UTC, kevinmost commented on keyboards/keebio/sinc/rev3/keymaps/vial/rules.mk
> +ENCODER_MAP_ENABLE = yes
Done.

2023-04-13 11:42 UTC, kevinmost reviewed
Hey, just pinging for a re-review when either of you gets a chance. Thanks.

2023-04-13 20:26 UTC, lesshonor requested changes
...so, one wrench in the gears is that at this point [there's a pending branch to pull in relatively recent QMK updates](https://github.com/vial-kb/vial-qmk/tree/merge-2023-03-12).

I have no control over pull requests, but I wouldn't expect this to be merged until after those changes are brought in. That way the changes you had to make to cover the 0.18.x to 0.20.x gap don't have to be dealt with later, and it's simpler to examine PRs for Vial keymaps that are *just* Vial keymaps.

One option might be retargeting your PR to that branch; it presumably wouldn't have to incorporate any keyboard-level changes that way.
(If you'd like, [you can also betatest the new version of the GUI](https://github.com/vial-kb/vial-gui/actions/runs/4463584822).)

2023-04-13 20:26 UTC, lesshonor commented on keyboards/keebio/sinc/rev1/config.h
> +#define ENCODERS_PAD_B_RIGHT { D4 }
```suggestion
```
If these are being moved to `info.json`, they don't need to be here.

2023-04-13 20:26 UTC, lesshonor commented on keyboards/keebio/sinc/rev2/config.h
> +#define ENCODERS_PAD_B_RIGHT { D4 }
```suggestion
```

2023-04-13 20:26 UTC, lesshonor commented on keyboards/keebio/sinc/rev3/config.h
> +#define ENCODERS_PAD_B_RIGHT { GP5 }
```suggestion
```

2023-10-14 01:49 UTC, closed without merging