Port Adelais en Ciel rev3
vial-kb/vial-qmk pull request #412
Opened 2023-03-14 16:37 UTC by stanrc85

Port for Adelais en Ciel rev3 PCB

2023-03-14 18:41 UTC, stanrc85 commented
I put the VIAL files in the `keyboards\mechlovin\adelais\rgb_led\rev3\keymaps` folder to avoid conflict with other PCB version keymaps but it seems to still call the `keyboards\mechlovin\adelais\keymaps\vial` files when compiling with `make mechlovin/adelais/rgb_led/rev3:vial -j 20`.  

If I rename `keyboards\mechlovin\adelais\rgb_led\rev3\keymaps\vial` to `keyboards\mechlovin\adelais\rgb_led\rev3\keymaps\vial2`  and compile with `make mechlovin/adelais/rgb_led/rev3:vial2 -j 20` then it compiles fine, no errors.

Any ideas?

2023-03-15 20:07 UTC, lesshonor commented
This is happening because of a bug that has since been fixed upstream: https://github.com/qmk/qmk_firmware/pull/18449

...Not sure what you want to do about that now, though. 🤷🏾

2023-03-15 21:10 UTC, stanrc85 commented
Ok good to know, I can mark it as draft until the next merge from QMK. Thanks

2023-04-10 01:54 UTC, stanrc85 commented
This can be merged now that https://github.com/vial-kb/vial-qmk/pull/432 has been merged, there is no longer a conflict in the keymap folders

2023-04-13 02:03 UTC, lesshonor requested changes
> This can be merged now that https://github.com/vial-kb/vial-qmk/pull/432 has been merged, there is no longer a conflict in the keymap folders

~~[It still doesn't build, though.](https://github.com/lesshonor/vial-qmk/actions/runs/4684144345/jobs/8299976716#step:8:258)~~

~~(I get the same result locally, for the record.)~~

My mistake, [I needed to update that CI test branch with the latest changes](https://github.com/lesshonor/vial-qmk/actions/runs/4684900594/jobs/8301506750#step:9:324). You should still fix all the other problems, though.

2023-04-13 02:03 UTC, lesshonor commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/vial.json
> +],
```suggestion
```
VIA ≠ Vial. Did you test this?

2023-04-13 02:03 UTC, lesshonor commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/vial.json
> +      {"name": "Backlight Toggle", "title": "Backlight Toggle", "shortName": "RGB BL TOG"}
If you're going to use these, they should match up with the custom keycodes in your keymap. [Please review the custom keycodes documentation](https://get.vial.today/manual/custom_keycode.html). None of the shortnames match your keycodes and six of them are just "Backlight Toggle" repeated...

2023-04-13 02:03 UTC, lesshonor commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/vial.json
> +          "3,1\n\n\n3,1\n\n\n\n\n\ne0"
Again: VIA ≠ Vial. This will not work. [Please review the porting guide for encoders](https://get.vial.today/docs/encoders.html), which also points out how you should edit the `keymap.c` and `rules.mk` files to make the encoder remappable in the Vial GUI.

2023-04-13 02:03 UTC, lesshonor commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/keymap.c
> +  BL_DVAL = USER09
```suggestion
  BL_EFFECT,
  BL_ISPD,
  BL_DSPD,
  BL_IHUE,
  BL_DHUE,
  BL_ISAT,
  BL_DSAT,
  BL_IVAL,
  BL_DVAL
```

2023-04-13 14:00 UTC, stanrc85 commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/vial.json
> +],
Yes it was working, I've removed it now though

2023-04-13 14:07 UTC, stanrc85 commented on keyboards/mechlovin/adelais/rgb_led/rev3/keymaps/vial/vial.json
> +          "3,1\n\n\n3,1\n\n\n\n\n\ne0"
~~I've addressed the other changes but I'm having trouble with this one.  I've followed the guide linked and was able to get the encoder showing up in Vial and confirmed it works, however it doesn't seem to pull the keycodes set in `ENCODER_MAP` (https://github.com/vial-kb/vial-qmk/pull/412/files#diff-183689fe221bd50de8bd5fb051724e956780d0f5edbce0f50c0f89103b13022fR61) and if I manually set them in Vial and disconnect the board, my changes are lost when I reconnect. Any ideas what I missed?~~ 

It works!

2023-04-16 01:10 UTC, merged