Add Koolertron AMAG09 9 key macropad
vial-kb/vial-qmk pull request #421
Opened 2023-03-23 04:35 UTC by al177

Added default and vial keymaps for the Koolertron AMAG09. This is a cheap and available board based on an ATMEGA32A that ships with a rebranded Vial firmware and GUI (MYKB).

2023-03-24 19:39 UTC, lesshonor requested changes

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/amag09.h
> +#define LAYOUT_all( \
If you've only got one layout, you can just use `LAYOUT`.

```suggestion
#define LAYOUT( \
```
By the way, you probably want to move this layout/matrix info into `info.json` and then delete this file. This is one of those things that works now, but will eventually break. [You can see other examples of how this works in the repository](https://github.com/vial-kb/vial-qmk/blob/47721416a6483a1d759c21a18beae3c0cb7d3eb2/keyboards/jacky_studio/piggy60/info.json), and/or run `qmk info -f json -kb koolertron/amag09` for an idea of the syntax (though that command ends up with some duplicate data)

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/config.h
> +
Don't need to include `config_common.h`.
```suggestion
```
You can move the matrix pins, diode direction and backlight pin into `info.json` too.

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/config.h
> +
This is the default, so you don't need to specify it.
```suggestion
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/default/keymap.c
> +  [BASE] = LAYOUT_all(
```suggestion
  [BASE] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/default/keymap.c
> +  [FN1] = LAYOUT_all(
```suggestion
  [FN1] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/default/keymap.c
> +  [FN2] = LAYOUT_all(
```suggestion
  [FN2] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/default/keymap.c
> +  [FN3] = LAYOUT_all(
```suggestion
  [FN3] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/vial/keymap.c
> +  [BASE] = LAYOUT_all(
```suggestion
  [BASE] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/vial/keymap.c
> +  [FN1] = LAYOUT_all(
```suggestion
  [FN1] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/vial/keymap.c
> +  [FN2] = LAYOUT_all(
```suggestion
  [FN2] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/vial/keymap.c
> +  [FN3] = LAYOUT_all(
```suggestion
  [FN3] = LAYOUT(
```

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/amag09.c
You can delete this file.

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/rules.mk
You could move all this into `info.json` too. Like most of my other suggestions, this is something that works fine now but will probably break eventually.

2023-03-24 19:39 UTC, lesshonor commented on keyboards/koolertron/amag09/keymaps/vial/config.h
> +/* VIAL_INSECURE = yes */
```suggestion
```

2023-03-25 04:54 UTC, al177 commented on keyboards/koolertron/amag09/amag09.h
> +#define LAYOUT_all( \
Done.

2023-03-25 04:55 UTC, al177 commented on keyboards/koolertron/amag09/config.h
> +
Done.

2023-03-25 04:56 UTC, al177 commented on keyboards/koolertron/amag09/config.h
> +
Yep, moved everything from amag09.[ch] and config.h to info.json

2023-03-25 04:56 UTC, al177 commented on keyboards/koolertron/amag09/amag09.c
Done

2023-03-25 04:57 UTC, al177 commented on keyboards/koolertron/amag09/rules.mk
Thanks for the review and tips!

2023-03-25 12:12 UTC, lesshonor approved these changes

2023-03-29 01:48 UTC, merged