[Keyboard] Adding support for OSAv2
vial-kb/vial-qmk pull request #425
Opened 2023-03-24 02:24 UTC by blindassassin111

Adding the OSAv2 MX PCB.

2023-03-24 19:28 UTC, lesshonor requested changes
...You might want to set this as draft until the latest updates from upstream hit, since it doesn't compile as-is.

2023-03-24 19:28 UTC, lesshonor commented on keyboards/viktus/osav2/keymaps/vial/rules.mk
> +VIAL_INSECURE = yes
```suggestion
```

2023-03-24 19:28 UTC, lesshonor commented on keyboards/viktus/osav2/keymaps/vial/rules.mk
> +VIALRGB_ENABLE = yes
```suggestion
```
`VIALRGB` is only for `RGB_MATRIX`.

2023-03-24 19:59 UTC, blindassassin111 commented on keyboards/viktus/osav2/keymaps/vial/rules.mk
> +VIAL_INSECURE = yes
Oops. I thought I had removed this. Sorry.

2023-03-24 20:02 UTC, blindassassin111 commented
> ...You might want to set this as draft until the latest updates from upstream hit, since it doesn't compile as-is.

Done. Hopefully the wait isn't too long. How will I know when to come back and take it off draft?

2023-03-24 20:50 UTC, lesshonor commented
> Done. Hopefully the wait isn't too long. How will I know when to come back and take it off draft?

Testing is happening [right now](https://github.com/vial-kb/vial-qmk/tree/merge-2023-03-12) but I don't have an ETA. I can just drop a comment here if you want...

2023-07-17 12:43 UTC, lesshonor commented
You can un-draft this now, but you'll need to make some changes [given that `viktus/osav2` now exists in the `vial` branch](https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/viktus/osav2).

2023-10-14 01:49 UTC, closed without merging