Waterfowl support
vial-kb/vial-qmk pull request #436
Opened 2023-04-03 12:11 UTC by JW2586

Implemented support for the Waterfowl keyboard with Vial. Supports 4 individually configurable encoders.

2023-04-10 01:04 UTC, xyzz requested changes

2023-04-10 01:04 UTC, xyzz commented on keyboards/waterfowl/keymaps/vial/compile command.txt
> +qmk compile -kb waterfowl -km vial
Delete this file

2023-04-12 22:30 UTC, lesshonor requested changes

2023-04-12 22:30 UTC, lesshonor commented on keyboards/waterfowl/keymaps/vial/rules.mk
> +VIAL_ENCODERS_ENABLE = yes
```suggestion
```
This doesn't do anything anymore.

2023-04-13 13:00 UTC, lesshonor approved these changes

2023-04-16 01:09 UTC, merged