Add reviung53 vial directory
vial-kb/vial-qmk pull request #440
Opened 2023-04-11 18:20 UTC by DPoplin

This PR adds a Reviung53 vial directory and keymap files.

2023-04-12 22:30 UTC, lesshonor requested changes

2023-04-12 22:30 UTC, lesshonor commented on keyboards/reviung/reviung53/keymaps/vial/rules.mk
> +VIAL_INSECURE = yes
```suggestion
```

`VIAL_INSECURE = yes` is [not permitted in the main `vial-qmk` repository](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination).

2023-04-12 22:30 UTC, lesshonor commented on keyboards/reviung/reviung53/keymaps/vial/readme.md
Is this file really necessary?

2023-04-17 14:24 UTC, DPoplin commented
Requested changes have been resolved. Please let me know if you need anything else

2023-04-17 19:27 UTC, lesshonor requested changes

2023-04-17 19:27 UTC, lesshonor commented on keyboards/reviung/reviung53/readme.md
Please restore this file. It was `readme.md` *within the Vial keymap folder* that I asked about. The keyboard-level file actually contains useful information...

2023-04-17 19:27 UTC, lesshonor commented on keyboards/reviung/reviung53/keymaps/vial/config.h
Please review [the documentation I linked earlier](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination), and remember to test changes locally. Without an unlock combination, this keymap won't compile.

2023-04-19 17:34 UTC, DPoplin commented
Requested changes should now be correctly implemented -- Firmware compiles

2023-04-20 00:28 UTC, lesshonor approved these changes

2023-05-01 01:36 UTC, merged