add support for kyria keyboard
vial-kb/vial-qmk pull request #441
Opened 2023-04-18 16:20 UTC by nosarthur

2023-04-27 22:26 UTC, lesshonor requested changes
You need to move this keymap under `splitkb/kyria/rev2`, because rev1 and rev2 don't have the same matrix:
https://github.com/vial-kb/vial-qmk/blob/8356266e078cefeec7c1e4a8c1d59118ad5a0755/keyboards/splitkb/kyria/rev1/rev1.h#L41
https://github.com/vial-kb/vial-qmk/blob/8356266e078cefeec7c1e4a8c1d59118ad5a0755/keyboards/splitkb/kyria/rev2/rev2.h#L41

2023-04-27 22:26 UTC, lesshonor commented on keyboards/splitkb/kyria/keymaps/vial/rules.mk
> +
```suggestion
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
```
Most this stuff is replicated from the keyboard level.
The Vial keymap in the main repo shouldn't overwrite the bootloader.

2023-04-30 18:11 UTC, nosarthur commented on keyboards/splitkb/kyria/keymaps/vial/rules.mk
> +
I have deleted some options that are identical to the keyboard level. Some are left here to reduce the firmware size

2023-05-01 01:15 UTC, lesshonor requested changes

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +MCU = atmega32u4
```suggestion
```
https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/keyboards/splitkb/kyria/rules.mk#L2
This is already set to the exact same value at the keyboard level.

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +
```suggestion
```
This is set at the keyboard level: https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/keyboards/splitkb/kyria/rules.mk#L5
Undoing this to put `caterina` here means `QK_BOOT` and flashing from the command line won't work the same way it does for all other builds of the Kyria. Your personal keymap, sure, but this is not an appropriate change for the de-facto Vial keymap.

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
If you're really concerned about file size, leaving mousekeys disabled frees up around 1800 bytes.

```suggestion
MOUSEKEY_ENABLE = yes 		# Mouse keys
```
`BOOTMAGIC_ENABLE` is forcibly set to yes if `VIA_ENABLE` is set to `yes`, so attempting to set it to `no` here does nothing: https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/builddefs/common_features.mk#L609-L615

`EXTRAKEY_ENABLE = yes` is already set at the keyboard level: https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/keyboards/splitkb/kyria/rules.mk#L12

`SLEEP_LED_ENABLE` is disabled by default, so attempting to set it to `no` here does nothing: https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/builddefs/common_features.mk#L530-L535

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +ENCODER_ENABLE = yes
```suggestion
```
This is already set at the revision level: https://github.com/vial-kb/vial-qmk/blob/4eb1c2e21fef3b2a94215992158c0195b92a8d4d/keyboards/splitkb/kyria/rev2/rules.mk#L3

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +DEFERRED_EXEC_ENABLE = no
```suggestion
```
This is disabled by default.

2023-05-01 01:15 UTC, lesshonor commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +
```suggestion
```
These are also disabled by default.

2023-05-06 16:19 UTC, nosarthur commented on keyboards/splitkb/kyria/rev2/keymaps/vial/rules.mk
> +SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
good to know, thanks. I was desperate to try various options to reduce the firmware size

2023-05-06 21:27 UTC, lesshonor approved these changes

2023-05-14 01:12 UTC, merged