Adding KBDFans D45
vial-kb/vial-qmk pull request #442
Opened 2023-04-19 20:26 UTC by DPoplin

Adding KBDFans D45 and adding Vial functionality

2023-04-28 22:44 UTC, lesshonor requested changes
You don't need to move the keymaps, but you do need to move the keyboard definition files to `kbdfans/d45/v1`, because `kbdfans/d45/v2` [already exists upstream and is pending a merge into Vial](https://github.com/vial-kb/vial-qmk/tree/merge-2023-03-12/keyboards/kbdfans/d45/v2).

2023-04-28 22:44 UTC, lesshonor commented on keyboards/kbdfans/d45/d45.c
This file should be removed (it isn't needed)

2023-04-28 22:44 UTC, lesshonor commented on keyboards/kbdfans/d45/d45.h
This file should be removed (it isn't needed)

2023-04-28 22:44 UTC, lesshonor commented on keyboards/kbdfans/d45/config.h
> +#define PRODUCT D45
At the very least, `PRODUCT` needs to be quoted:
```suggestion
#define DEVICE_VER 0x0001
#define PRODUCT "D45"
```
In the near future, the USB information needs to be [moved from `config.h` to `info.json`](https://docs.qmk.fm/#/ChangeLog/20221126?id=usb-ids-refactoring). If you don't at least quote the keyboard name, this keyboard will stop compiling when [the changes in this branch](https://github.com/vial-kb/vial-qmk/tree/merge-2023-03-12) are merged into the `vial` branch. That merge may or may not happen before your PR is even accepted.

This general advice to migrate keyboard-level information `info.json` goes for matrix pins, diode direction, MCU and bootloader, and you should apply it to any PR you open that adds keyboards which don't exist upstream. [Please see other examples of how this works in the repository](https://github.com/vial-kb/vial-qmk/blob/vial/keyboards/viktus/minne/info.json). You can also run `qmk info -f json -kb kbdfans/d45/v1` to assist with the conversion (after you move this keyboard to the v1 folder)

2023-04-28 22:44 UTC, lesshonor commented on keyboards/kbdfans/d45/config.h
> +#define VIAL_KEYBOARD_UID {0xC0, 0x17, 0xF0, 0x89, 0xD6, 0x68, 0xC4, 0xEA}
You already have this in `vial/config.h`.
```suggestion
```

2023-05-15 15:50 UTC, DPoplin commented on keyboards/kbdfans/d45/config.h
> +#define PRODUCT D45
Moved to info.json along with the other bootloader/diode/mcu/lighting/etc.

2023-05-20 18:01 UTC, merged