Add support for Keebio DSP40
vial-kb/vial-qmk pull request #443
Opened 2023-04-19 21:36 UTC by DPoplin

Add vial support for keebio/dsp40

2023-04-19 23:12 UTC, lesshonor requested changes

2023-04-19 23:12 UTC, lesshonor commented on keyboards/keebio/dsp40/rev1/rules.mk
> +NKRO_ENABLE = yes            # Enable N-Key Rollover
```suggestion
NKRO_ENABLE = no            # Enable N-Key Rollover
```
Modifications at the keyboard level that are inconsistent with QMK upstream will cause conflicts later down the road. If you want this change, [submit a PR to QMK](https://github.com/qmk/qmk_firmware/pulls). Otherwise, confine it to the Vial keymap's `rules.mk` file.

2023-04-19 23:12 UTC, lesshonor commented on keyboards/keebio/dsp40/keymaps/vial/vial.json
> +    ],
```suggestion
    "lighting": "qmk_backlight",
```
Vial ≠ VIA.

2023-04-19 23:12 UTC, lesshonor commented on keyboards/keebio/dsp40/keymaps/vial/keymap.c
This board supports an encoder that is enabled by default, so you should probably [allow people to map it in Vial](https://get.vial.today/docs/encoders.html).

2023-04-19 23:43 UTC, DPoplin commented on keyboards/keebio/dsp40/keymaps/vial/keymap.c
This is a good callout. I'll work on adding that in

2023-04-22 18:42 UTC, lesshonor requested changes

2023-04-22 18:42 UTC, lesshonor commented on keyboards/keebio/dsp40/dsp40.c
Please revert all changes to this file -- remember what I said about keyboard-level changes that don't match upstream QMK causing problems later? This counts.

2023-04-22 18:42 UTC, lesshonor commented on keyboards/keebio/dsp40/rev1/rev1.c
Revert all changes to this file; see previous comment for explanation.

2023-04-28 13:35 UTC, lesshonor approved these changes

2023-05-01 01:35 UTC, merged