Update and add Budget96 support
vial-kb/vial-qmk pull request #450
Opened 2023-04-26 17:44 UTC by DonutCables

Updated Budget96 to remove deprecated ```RGBLIGHT_ENABLE``` and addition of Vial-enabled default map,

2023-04-27 20:31 UTC, lesshonor requested changes

2023-04-27 20:31 UTC, lesshonor commented on keyboards/donutcables/budget96/config.h
I wouldn't bother modifying this file; the pending merge from upstream [already makes this change and more](https://github.com/vial-kb/vial-qmk/blob/merge-2023-03-12/keyboards/donutcables/budget96/config.h). Updating it now will cause a conflict.

2023-04-27 20:55 UTC, DonutCables commented on keyboards/donutcables/budget96/config.h
Ok I think I managed to properly remove the commit for that file so it should just be the map updates now.

2023-04-27 23:00 UTC, lesshonor approved these changes

2023-04-27 23:00 UTC, lesshonor commented on keyboards/donutcables/budget96/keymaps/vial/rules.mk
> +RAW_ENABLE = no
```suggestion
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no
NKRO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
```
Almost all of this isn't enabled by default (and `BLUETOOTH_ENABLE` is misspelled)
`VIA_ENABLE = yes` forcibly enables both `BOOTMAGIC` and `RAW`, so no point trying to set them to `no`

Though ultimately, having junk in your Vial rules.mk doesn't matter since it'll just be ignored.

2023-04-28 19:04 UTC, lesshonor requested changes
...Should have actually looked at your keymap. 🙃

2023-04-28 19:04 UTC, lesshonor commented on keyboards/donutcables/budget96/keymaps/vial/keymap.c
> +      KC_ESC,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,    KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_NLCK, KC_INS,  KC_HOME, KC_PGUP, KC_PSLS,
```suggestion
      KC_ESC,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,    KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_NUM, KC_INS,  KC_HOME, KC_PGUP, KC_PSLS,
```

2023-04-28 19:04 UTC, lesshonor commented on keyboards/donutcables/budget96/keymaps/vial/keymap.c
> +      QK_BOOT,   EEP_RST,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,
```suggestion
      QK_BOOT, EE_CLR,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS,
```

2023-04-28 19:04 UTC, lesshonor commented on keyboards/donutcables/budget96/keymaps/vial/keymap.c
> +      BL_TOGG, BL_STEP,  BL_ON,   BL_OFF,  BL_INC,  BL_DEC,  BL_BRTG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
Not exactly a dealbreaker, but since you've got backlight disabled, are you sure you want backlight codes here?
```suggestion
      KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
```

2023-04-30 23:24 UTC, merged