[Keyboard] Add Moondrop Dash75
vial-kb/vial-qmk pull request #462
Opened 2023-05-18 00:45 UTC by vinorodrigues

## Description

Add the Moondrop Dash75 - an innovative 75% keyboard with integrated USB Hub and headphone DAC/Amp

## Upstream

* This ports https://github.com/qmk/qmk_firmware/pull/20890 to **Vial-QMK**
    * and adds the `vail` keymap
    * `via` keymap is forlorn

## Types of Changes
* [X] Keyboard (addition or update)
* [X] Keymap/layout/userspace (addition or update)

2023-05-18 21:32 UTC, lesshonor requested changes
So, the upstream version of `moondrop/dash75/r1/config.h` has [`#define SERIAL_NUMBER Dash 75`](https://github.com/qmk/qmk_firmware/blob/1aa52124cab7fef299b1031eb527a63de9562667/keyboards/moondrop/dash75/r1/config.h#L6).

...You know this will cause a problem with Vial, which is why it's not in this PR. But it is worth noting that this difference will cause conflicts whenever changes to that file are pulled from upstream, which someone (i.e. xyz) will need to continually monitor and resolve.

I'm not xyz, so maybe he doesn't mind -- but I don't think I'd accept any keymaps to the main repository that are guaranteed to require that kind of babysitting.

2023-05-18 21:32 UTC, lesshonor commented on keyboards/moondrop/dash75/info.json
> +        "device_version": "1.5.0"
```suggestion
        "device_version": "1.6.0"
```

2023-05-18 21:39 UTC, vinorodrigues commented on keyboards/moondrop/dash75/info.json
> +        "device_version": "1.5.0"
yeah... the v1.5 for Vial is already avail for download, but this has the incorrect VID/PID.  For the Vial version we increment the version by .1 to inform users who prefer the Vial build over the QMK/VIA build to get this newer one.
*(btw - this is not the only delta, we also needed to remove the `SERIAL_NUMBER` define as Vial uses that to self-identify on the app.)*
I am not aware of any rule that stipulates an exact match to upstream ... if this is so the we'd need to adjust the assumptions on these PR's.

2023-05-18 21:52 UTC, vinorodrigues commented
> So, the upstream version of `moondrop/dash75/r1/config.h` has `#define SERIAL_NUMBER Dash 75`.

One thing to consider on this keyboard is that it is targeted to the audiophile consumer - it is constructed with the USB connected to a 4 port-hub, with two USB- Type-A receptacles exposed, then the next two ports have one connected to MOONRIVER 2 Dual CS43198 DAC, and the other to a rudimentary ATMega32U4 based keyboard. 

The DAC identifies itself with an OEM PID/VID, and a SERIAL NUMBER descriptor as "Moonriver 2".  The s/n on the QMK aligns this branding to the KB too.  Like you said - this does not work with the Vial variant as the App fails to identify the KB as a Vial enabled KB, so was removed for the Vial variant of the code.

2023-05-20 18:03 UTC, xyzz commented
Can you keep the "define" in moondrop/dash75/r1/config.h and then "undef" it in the vial config.h?

2023-05-20 19:28 UTC, vinorodrigues commented
> Can you keep the "define" in moondrop/dash75/r1/config.h and then "undef" it in the vial config.h?

Unfortunately not - the sequence of includes means that the `SERIAL_NUMBER` defined in vial code occurs before the inclusion of the kb or keymap `config.h` ... so the define hits an error from the onset.

```bash
Compiling: .build/obj_moondrop_dash75_r1/src/default_keyboard.c                                    In file included from <command-line>:
./keyboards/moondrop/dash75/r1/config.h:6: error: "SERIAL_NUMBER" redefined [-Werror]
 #define SERIAL_NUMBER "Dash 75"
```

I will change the code to use a `#ifndef` ... but that will still be different from QMK upstream anyway.  *(So deleting the def or wrapping it in a `#ifndef` will result in the same outcome.)*

2023-05-20 21:29 UTC, merged