Add imi60 support
vial-kb/vial-qmk pull request #475
Opened 2023-06-04 20:26 UTC by key10iq

This PR adds Vial and QMK support for imi60. It is a PCB for two future keyboards currently in prototyping.
Flashed and tested successfully.

2023-06-05 02:54 UTC, lesshonor requested changes

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/config.h
Delete this file; it is unnecessary.

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/imi60.c
Delete this file; it is unnecessary.

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/imi60.h
Delete this file; it is unnecessary (the matrix information is already in `info.json`)

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/keymaps/default/keymap.c
> +
Don't need to have extra blank layers
```suggestion
)
```

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/keymaps/vial/keymap.c
> +
Don't need to have extra blank layers, these will be automatically filled in
```suggestion
)
```

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/keymaps/vial/rules.mk
> +VIAL_INSECURE = yes
```suggestion
```
[Per the documentation](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination):
> keyboards which enable `VIAL_INSECURE` will not be accepted to the main `vial-qmk` repository.

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/rules.mk
> +LTO_ENABLE = yes
You already set all this information in `info.json` and that is where it belongs. The `BOOTLOADER` here actually contradicts what you've got there, so make sure it is correct in `info.json`...

```suggestion
# This file intentionally left blank
```

2023-06-05 02:54 UTC, lesshonor commented on keyboards/keyten/imi60/info.json
> +    "maintainer": "qmk",
```suggestion
    "maintainer": "key10iq",
```

2023-06-05 16:06 UTC, lesshonor requested changes
[Doesn't build](https://github.com/lesshonor/vial-qmk/actions/runs/5179271237/jobs/9331934518). Here's [a hint](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination).

Don't forget to test these changes on your PCB.

2023-06-05 16:52 UTC, key10iq commented
> [Doesn't build](https://github.com/lesshonor/vial-qmk/actions/runs/5179271237/jobs/9331934518). Here's [a hint](https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination).
> 
> Don't forget to test these changes on your PCB.

Tested. Works.
Thanks for the tip!

2023-06-06 03:22 UTC, lesshonor approved these changes

2023-06-18 22:14 UTC, merged