Ported nack to VIAL
vial-kb/vial-qmk pull request #486
Opened 2023-06-24 20:24 UTC by farfalleflickan

Ported the default keymap to VIAL

2023-06-24 22:59 UTC, lesshonor requested changes

2023-06-24 22:59 UTC, lesshonor commented on keyboards/nack/keymaps/vial/vial.json
> +        "labels": ["BASE", "NUM", "FN"],
```suggestion
```
[These aren't layer labels.](https://get.vial.today/docs/porting-to-via.html#create-layout-options)

2023-06-24 22:59 UTC, lesshonor commented on keyboards/nack/keymaps/vial/keymap.c
> +       _______,     _______,     _______,     MO(FN),      KC_NO,       KC_NO,       TO(BASE),    _______,     KC_GRV,      KC_NO,       KC_NO,       KC_NO,       KC_NO
https://github.com/vial-kb/vial-qmk/blob/52e5b55a4aec0653df9cd0f5709b0d9b4ea7ce66/docs/feature_layers.md?plain=1#L9

```suggestion
       _______,     _______,     _______,     KC_TRNS,      KC_NO,       KC_NO,       TO(BASE),    _______,     KC_GRV,      KC_NO,       KC_NO,       KC_NO,       KC_NO
```
I don't really get the use of `TO(BASE)` here since you only use momentary layer holds, but that's at least not wrong.

2023-06-24 22:59 UTC, lesshonor commented on keyboards/nack/keymaps/vial/keymap.c
> +       KC_NO,       KC_NO,       KC_NO,       MO(NUM),     KC_NO,       KC_NO,       TO(BASE),    KC_NO,       KC_NO,       KC_NO,       KC_NO,       RGB_VAD,     KC_NO
https://github.com/vial-kb/vial-qmk/blob/52e5b55a4aec0653df9cd0f5709b0d9b4ea7ce66/docs/feature_layers.md?plain=1#L46
```suggestion
       KC_NO,       KC_NO,       KC_NO,       KC_TRNS,     KC_NO,       KC_NO,       KC_TRNS,    KC_NO,       KC_NO,       KC_NO,       KC_NO,       RGB_VAD,     KC_NO
```
The `TO(BASE)` needs to be transparent because of the `MO(FN)` call on the first layer, and activating a lower layer with `MO(NUM)` from this upper layer isn't going to do anything since you have nothing but `KC_NO` instead of `KC_TRNS`.

2023-06-25 00:23 UTC, farfalleflickan commented
The weirdness with the layers is mostly because of copy/pasting and never bothering to fix it.

2023-06-25 04:56 UTC, xyzz requested changes

2023-06-25 04:56 UTC, xyzz commented on keyboards/nack/keymaps/vial/readme.md
> +# The default keymap for nack, simple and minimal.
Delete this file

2023-06-25 08:42 UTC, merged