vial port of kprepublic/bm65hsrgb
vial-kb/vial-qmk pull request #513
Opened 2023-07-31 21:26 UTC by nils-a

2023-08-06 14:57 UTC, xyzz requested changes

2023-08-06 14:57 UTC, xyzz commented on keyboards/kprepublic/bm65hsrgb/keymaps/vial/readme.md
> +# The vial keymap for bm65rgb
Delete this file

2023-08-07 07:44 UTC, nils-a commented on keyboards/kprepublic/bm65hsrgb/keymaps/vial/readme.md
> +# The vial keymap for bm65rgb
done. 👍

2023-08-09 15:11 UTC, lesshonor requested changes

2023-08-09 15:11 UTC, lesshonor commented on keyboards/kprepublic/bm65hsrgb/keymaps/vial/rules.mk
> +LTO_ENABLE = yes
```suggestion
```
You don't need to cut-paste all the stuff that's already set in `rev1/rules.mk`.

2023-08-14 21:16 UTC, lesshonor approved these changes

2023-08-18 17:00 UTC, merged