Added Madeline
vial-kb/vial-qmk pull request #531
Opened 2023-08-28 18:20 UTC by NCKiser

Added Madeline keyboard, default and vial keymaps
PCB by Rossman360, firmware ported to QMK 1.1.1 / Vial 0.7 by NCKiser/kiserdesigns
Case and PCB Group-Buy by rubybuilds

Tested both keymaps on actual hardware.
More kiserdesigns keyboard to come in the near future.

2023-08-29 22:08 UTC, lesshonor requested changes

2023-08-29 22:08 UTC, lesshonor commented on keyboards/kiserdesigns/madeline/keymaps/vial/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`.
```suggestion
```

2023-08-29 22:08 UTC, lesshonor commented on keyboards/kiserdesigns/madeline/keymaps/vial/keymap.c
> +    [7] =   { ENCODER_CCW_CW(KC_NO, KC_NO) }
```suggestion
    [1] =   { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [2] =   { ENCODER_CCW_CW(KC_NO, KC_NO) }
```

2023-08-29 22:08 UTC, lesshonor commented on keyboards/kiserdesigns/madeline/keymaps/vial/rules.mk
> +VIAL_INSECURE = no
```suggestion
ENCODER_MAP_ENABLE = yes
```
The rest are on by default or no longer needed.

2023-08-29 22:08 UTC, lesshonor commented on keyboards/kiserdesigns/madeline/keymaps/vial/vial.json
> +    "productId": "6D64",
```suggestion
```
You can leave them if you want, but these technically aren't necessary.

2023-08-29 23:11 UTC, NCKiser commented on keyboards/kiserdesigns/madeline/keymaps/vial/vial.json
> +    "productId": "6D64",
I honestly thought they were needed. I always forget to update the vid and pid in vial.json when writing new firmware, glad to know they can be omitted!

2023-08-30 00:34 UTC, NCKiser commented on keyboards/kiserdesigns/madeline/keymaps/vial/keymap.c
> +    [7] =   { ENCODER_CCW_CW(KC_NO, KC_NO) }
Turns out the encoder and keymap layers defined still need to match, even if they are both padded by Vial

2023-08-30 02:27 UTC, lesshonor approved these changes
Builds for me.

2023-09-03 04:37 UTC, merged