add vial for 2% milk keyboard
vial-kb/vial-qmk pull request #548
Opened 2023-09-19 20:58 UTC by Kuznetsov-s-v

Hello, I've created a port vial for the 2% milk keyboard by spaceman.

2023-09-22 01:16 UTC, lesshonor requested changes

2023-09-22 01:16 UTC, lesshonor commented on keyboards/spaceman/2_milk/keymaps/vial/config.h
> +#define VIAL_KEYBOARD_UID {0x3B, 0x6B, 0xA0, 0x29, 0x80, 0x56, 0xED, 0xD1}
[Duplicate UID](https://github.com/lesshonor/vial-qmk/actions/runs/6268859061/job/17024458099#step:3:385). You'll need to generate a different one.

2023-09-22 01:16 UTC, lesshonor commented on keyboards/spaceman/2_milk/keymaps/vial/vial.json
> +  "name": "m2",
```suggestion
```

2023-09-30 19:24 UTC, Lenbok commented
Already addressed by #539

2023-10-01 18:36 UTC, Lenbok commented
Sorry, my message was probably too brief. This PR is no longer needed and should be closed. Another PR that adds support for this keyboard had already been created, and it was recently merged.

2023-10-01 20:53 UTC, closed without merging