Port MonsGeek M1 to Vial
vial-kb/vial-qmk pull request #550
Opened 2023-09-26 01:14 UTC by adophoxia

As title.

2023-09-28 03:29 UTC, lesshonor requested changes

2023-09-28 03:29 UTC, lesshonor commented on keyboards/monsgeek/m1/keymaps/vial/vial.json
> +    ],
```suggestion
```
Not sure how this got here.

2023-09-28 03:29 UTC, lesshonor commented on keyboards/monsgeek/m1/keymaps/vial/vial.json
> +      "presets": {"Default": [0,0]},
```suggestion
```
What does this do?

2023-09-28 05:02 UTC, adophoxia commented on keyboards/monsgeek/m1/keymaps/vial/vial.json
> +      "presets": {"Default": [0,0]},
From Xelus via the VIA server:
> presets for the layout options
like default hhkb vs normal 60

2023-09-28 13:22 UTC, lesshonor commented on keyboards/monsgeek/m1/keymaps/vial/vial.json
> +      "presets": {"Default": [0,0]},
What does this do *in Vial*, though?

To cut to the chase: even if it worked, it doesn't seem very useful because the 0th options are already the default.

2023-09-29 02:32 UTC, adophoxia commented on keyboards/monsgeek/m1/keymaps/vial/vial.json
> +      "presets": {"Default": [0,0]},
Probably nothing if I were to hypothesize if the GUI never took this into account. I'll just remove it for convenience's sake.

2023-09-30 17:43 UTC, lesshonor approved these changes

2023-09-30 18:20 UTC, merged