[Keyboard] Add Kimiko Rev2 and update Rev1
vial-kb/vial-qmk pull request #553
Opened 2023-09-27 10:49 UTC by BenRoe

- Add Kimiko Rev2 with VIAL keymap only.
- Remove Rev1 user keymaps and move VIAL keymap under rev1 folder, because Rev1 and Rev2 are different
- Update Rev1 migrated some into info.json

Rev1 and Rev2 code are tested on hardware.

2023-09-28 14:47 UTC, lesshonor requested changes
Since both the QMK and Vial-QMK repositories are on 0.22.x right now, the code you're [currently submitting](https://github.com/qmk/qmk_firmware/pull/21719)/plan to submit to QMK and the code in Vial should end up basically identical outside of the `vial` keymap folders. Please revise your PR with that in mind.

...There's kind of a lot to parse through here but I've left comments on some of the problems/differences.

2023-09-28 14:47 UTC, lesshonor commented on keyboards/keycapsss/kimiko/rev2/keymaps/vial/readme.md
Please delete this.
- The information in it isn't correct (this isn't the "via" keymap, there is no configuration anywhere for a pointing device)
- It's full of HTML code for some reason

It's not really needed anyway and most people won't look at it, so you may as well get rid of it.

2023-09-28 14:47 UTC, lesshonor commented on keyboards/keycapsss/kimiko/rev2/keymaps/vial/vial.json
> +    ],
```suggestion
```
Most of this is VIA v3 code that does nothing in Vial.

2023-09-28 14:47 UTC, lesshonor commented on keyboards/keycapsss/kimiko/rev2/config.h
This file duplicates a lot of things that are already set in `info.json`. It should be basically identical to [the one you're submitting to QMK](https://github.com/qmk/qmk_firmware/pull/21719/files#diff-c4699e727d0a568cf0cd4174faa38ac4aec8f9e4633f65278aa4025e83315add).

2023-09-28 14:47 UTC, lesshonor commented on keyboards/keycapsss/kimiko/keymaps/oriaj3/config.h
Leave this keymap alone; there's no need to delete or change anything about it at all since it wasn't designed or intended to be built using the Vial-QMK fork. Whatever eventually happens to it will be mirrored in this repository when changes are pulled from upstream in the future.

2023-09-28 14:47 UTC, lesshonor commented on keyboards/keycapsss/kimiko/rev1/info.json
> +                { "matrix": [9, 0], "x": 12, "y": 4.15 }
You don't need to change any of this.

2023-10-04 11:34 UTC, BenRoe commented on keyboards/keycapsss/kimiko/rev2/keymaps/vial/vial.json
> +    ],
Thanks for the hin. I removed it with the latest push.

2023-10-04 12:35 UTC, BenRoe commented
Mirrored the changes from the qmk repo. 
The rev1 vial keymap will change later, if the rev2 pr was merged and the rev1 code will refactored afterwards with a dev branch pr.

2023-10-09 01:59 UTC, xyzz commented
It fails to build

2023-10-10 08:27 UTC, BenRoe commented
> It fails to build

Fixed and all checks have passed.

2023-10-14 01:43 UTC, merged