Add vial support for Jorne
vial-kb/vial-qmk pull request #562
Opened 2023-10-01 12:27 UTC by shayna-ilya

Vial port for [Jorne keyboard ](https://github.com/joric/jorne)

2023-10-01 21:16 UTC, lesshonor requested changes

2023-10-01 21:16 UTC, lesshonor commented on keyboards/jorne/keymaps/vial/config.h
> +
```suggestion
```
This is the default, so no need to specify it.

2023-10-04 12:19 UTC, shayna-ilya commented on keyboards/jorne/keymaps/vial/config.h
> +
fixed it

2023-10-04 12:47 UTC, lesshonor approved these changes

2023-10-09 05:20 UTC, merged