Add vial support for Meletrix Zoom65
vial-kb/vial-qmk pull request #572
Opened 2023-10-12 23:59 UTC by OTLabs

Vial port for Meletrix Zoom65 keyboard,
https://zoom65.com/

2023-10-13 03:43 UTC, lesshonor requested changes

2023-10-13 03:43 UTC, lesshonor commented on keyboards/meletrix/zoom65/keymaps/vial/keymap.c
> +    ),
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
)
```

2023-10-13 03:43 UTC, lesshonor commented on keyboards/meletrix/zoom65/keymaps/vial/keymap.c
> +    [3] = { ENCODER_CCW_CW(_______, _______) },
```suggestion
    [1] = { ENCODER_CCW_CW(KC_MPRV, KC_MNXT) }
```

2023-10-13 03:43 UTC, lesshonor commented on keyboards/meletrix/zoom65/keymaps/vial/readme.md
No need to add this file. If someone doesn't know to look at the `rules.mk` to check features, they're not going to know what "QMK Settings" means either...and since it uses an atmega32u4 more things on it will probably end up having to be disabled in the future so it continues to build.

2023-10-13 03:43 UTC, lesshonor commented on keyboards/meletrix/zoom65/keymaps/vial/config.h
> +
```suggestion
```

2023-10-13 04:21 UTC, OTLabs commented on keyboards/meletrix/zoom65/keymaps/vial/readme.md
Sure, thank you! Fixed!

2023-10-14 01:42 UTC, merged

2023-10-14 03:09 UTC, OTLabs commented
Thank you for review and comments!