Add support for Aurora Corne by splitkb
vial-kb/vial-qmk pull request #589
Opened 2023-11-05 09:49 UTC by artursmirnov

Mostly just added a keymap layout for the keyboard and enabled Vial support following the guide. Tested the integration with my keyboard.

2023-11-07 02:56 UTC, lesshonor requested changes
> Tested the integration with my keyboard.

...I'm going to be charitable and assume that you're [using an ARM Micro](https://docs.qmk.fm/#/feature_converters?id=converters), because otherwise this keymap is *massively* oversize.

At present keymaps submitted to this repository still need to build for their original target platforms (i.e. AVR). The following resources may help:

- https://get.vial.today/docs/firmware-size.html
- https://docs.qmk.fm/#/squeezing_avr

2023-11-07 02:56 UTC, lesshonor commented on keyboards/splitkb/aurora/corne/keymaps/vial/keymap.json
> +    "keymap": "default",
```suggestion
    "keymap": "vial",
```

2023-11-07 02:56 UTC, lesshonor commented on keyboards/splitkb/aurora/corne/keymaps/vial/keymap.json
> +            "rgblight": false
```suggestion
            "rgblight": false,
            "via": true,
            "vial": true
```

2023-11-07 02:56 UTC, lesshonor commented on keyboards/splitkb/aurora/corne/keymaps/vial/rules.mk
> +VIAL_ENABLE = yes
I'd say that you could delete this file entirely but you probably want to start selectively disabling features here so the firmware actually builds. Here's an example of that syntax.
```suggestion
ifeq ($(strip $(MCU)), atmega32u4)
    QMK_SETTINGS = no
endif
```
...Also you can leave the huge license blob off `rules.mk` files. QMK's collaborators [have actually been trying to get splitkb's contractors to stop cut-pasting it in](https://github.com/qmk/qmk_firmware/pull/21499#issuecomment-1632697365).

2023-11-08 13:59 UTC, thomasbaart commented
Hi! We're starting to add Vial support for all our keyboards soon, so we'll either raise changes to this PR or raise a new PR once we're ready. Thanks for the pointers @lesshonor, I'll make sure we take them into account.

The license headers already existed in other firmware that did get approved, so we tried to match as closely to existing firmware as possible. The process isn't always uniform for every PR due to the nature of the project, so I reckon things need a little more ironing sometimes ;)

Now I'm here anyway: Would it be worthwhile to raise all keyboards as a single PR, so we can apply any desired changes in one swoop and have it all nice and equal?

2023-11-09 00:16 UTC, lesshonor commented
> Would it be worthwhile to raise all keyboards as a single PR, so we can apply any desired changes in one swoop and have it all nice and equal?

You can add and/or revise keymaps for all your boards in one fell swoop if you want. If everything passes CI checks it will almost certainly be merged (at xyz's convenience; I have no control over the process).

2024-02-10 06:45 UTC, xyzz commented
Closing because there's been no update for over a month.

2024-02-10 06:45 UTC, closed without merging