Add support for foostan Cornelius
vial-kb/vial-qmk pull request #590
Opened 2023-11-07 04:55 UTC by ebastler

This PR adds a vial keymap for the foostan cornelius board. It was tested on hardware and cornfirmed working. The keymap mirros the default/VIA keymaps upstream by foostan, since I believe these should be the default.

2023-11-08 02:17 UTC, lesshonor requested changes
If this were an ARM board I'd probably make these suggestions and still approve...but on AVR I think space conservation is important enough to request changes.

2023-11-08 02:17 UTC, lesshonor commented on keyboards/foostan/cornelius/keymaps/vial/keymap.c
> +  ),
No need to hardcode filler layers, especially on AVR. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
)
```

2023-11-08 02:17 UTC, lesshonor commented on keyboards/foostan/cornelius/keymaps/vial/readme.md
Not to be harsh...but even if this file provided crucial information, no one is going to bother looking at it. IMO, might as well delete.

2023-11-08 02:17 UTC, lesshonor commented on keyboards/foostan/cornelius/keymaps/vial/vial.json
> +  "productId": "0x0005",
```suggestion
```
Vial doesn't actually need these attributes here.

2023-11-12 09:38 UTC, xyzz commented
the mostly empty readme file needs to be deleted

2023-11-22 13:45 UTC, ebastler commented on keyboards/foostan/cornelius/keymaps/vial/readme.md
I just kept it around since it was there in the default keymap and I didn't change much about it... Will delete, thx.

2023-11-22 13:48 UTC, ebastler commented
I only kept the empty readme around since it was part of the original "default" keymap in QMK - removed it now.

2023-11-22 16:46 UTC, lesshonor approved these changes

2023-11-23 00:21 UTC, merged