Lotus 58, Vial keymap
vial-kb/vial-qmk pull request #591
Opened 2023-11-07 10:14 UTC by TweetyDaBird

Adding Vial keymap, updated to latest QMK keycodes and moved appropriate settings to info.JSON

2023-11-08 03:02 UTC, lesshonor requested changes

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +
...Is wedging in this blank layer really necessary?

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +    [3] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```suggestion
    [1] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
```

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +	oled_write_P(PSTR("\n"), false);
```suggestion
    oled_advance_page(true);
    oled_write_P(PSTR("Lotus -58-"), false);
    oled_advance_page(true);
```
Not sure exactly what the point of the blank string is, but using `advance_page` here will improve matrix scan rate (and means you don't have to store additional line breaks in `PROGMEM`)

If you know there will never be text in any of these areas (so they will never have to be cleared) you could use `oled_advance_page(false)` to eke out another tiny efficiency boost.

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +    oled_write_P(PSTR("\n"), false);
```suggestion
    oled_advance_page(true);
```

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +	oled_write_P(PSTR("\n"), false);
```suggestion
	oled_advance_page(true);
	oled_write_P(PSTR("Auto-Shift"), autoshift);
	oled_advance_page(true);
```

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +    return rotation;
```suggestion
	return OLED_ROTATION_270;
```

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +        print_status_narrow();
```suggestion
```

2023-11-08 03:02 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +}
```suggestion
```
Locking out layers with no way to determine what's going on from the Vial GUI definitely results in confusion. Users are being primed to look for [the tri-layer paradigm laid out in the QMK docs](https://docs.qmk.fm/#/feature_tri_layer) versus a `layer_state` callback.

2023-11-08 06:53 UTC, TweetyDaBird commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +
Nope, just a leftover from Lily58 firmware which I started with years ago.

2023-11-08 06:55 UTC, TweetyDaBird commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +}
Agreed, that was a carryover from QMK, so it's going away.

2023-11-08 11:27 UTC, lesshonor requested changes
I forgot to mention this in my original comment: if you really only want to provide this keymap for `nanoboot`, you can put it into a `keymaps` folder under `nanoboot`—i.e., `keyboards/tweetydabird/lotus58/nanoboot/keymaps/vial`.
But if I was you I would just selectively disable more features in the `rules.mk`. E.g.
```make
# Reduce size on atmega32u4
ifeq ($(strip $(MCU)), atmega32u4)
    TAP_DANCE_ENABLE = no
    QMK_SETTINGS = no
    KEY_OVERRIDE_ENABLE = no
    COMBO_ENABLE = no
    # Reduce size even more for non-nanoboot bootloaders
    ifneq ($(strip $(BOOTLOADER_SIZE)), 512)
        MAGIC_ENABLE = no
        MOUSEKEY_ENABLE = no
    endif
endif
```

2023-11-08 11:27 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/keymap.c
> +    }
Terribly sorry, I steered you slightly wrong here with my earlier suggestion. As you're printing the same thing on both sides, the entire `if` statement isn't necessary.
```suggestion
    print_status_narrow();
```

2023-11-08 12:54 UTC, TweetyDaBird commented
Yep, working on it and testing. 

Unfortunately a trip to the vet with the family cat got in between. Feeling a bit low right now, so I'll pick up later.

2023-11-11 19:10 UTC, lesshonor approved these changes
The keyboard-level change here is quite reasonable as the same change is being made in [an in-progress QMK PR](https://github.com/qmk/qmk_firmware/pull/22424).

2023-11-11 19:10 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/vial.json
> +
```suggestion
```
Technically not necessary for Vial.

2023-11-11 21:59 UTC, TweetyDaBird commented on keyboards/tweetydabird/lotus58/keymaps/vial/vial.json
> +
No, not necessary, but very beneficial as it shows as the device name in most OS's. Meaning it's easy to identify if a keyboard is flashed with vial or QMK.

2023-11-12 02:48 UTC, lesshonor commented on keyboards/tweetydabird/lotus58/keymaps/vial/vial.json
> +
That isn't determined by `vial.json`, but by `info.json`. [The Vial GUI concatenates `manufacturer` with `keyboard_name`](https://github.com/vial-kb/vial-gui/blob/f5ef91fc30915c6d6946f86d80bd2711e7de4463/src/main/python/vial_device.py#L54).

![I flashed an Elite-Pi with this PR](https://github.com/vial-kb/vial-qmk/assets/86894501/c92dc364-9768-410e-90c9-dbee2f1b373e).

(I hope your cat is doing better. If that isn't the case, my sympathies.)

2023-11-12 09:35 UTC, merged

2023-11-12 13:41 UTC, TweetyDaBird commented on keyboards/tweetydabird/lotus58/keymaps/vial/vial.json
> +
Hmmm.  Ok. Then we are editing that. 

No, unfortunately after 17 years of life, out of which 8 being my daughters life long companion/slash teddy bear/snuggle cat, she past. So yeah, cry fest.