Porting Inland mk47 from Via
vial-kb/vial-qmk pull request #602
Opened 2023-11-15 07:21 UTC by usrfriendly

This is a quick, effective port from Via to Vial for the Inland MK47 keyboard.  It appears to be fully featured and fully functional with only enough modification to add the required files/configurations Vial needs, simply following the porting guide, compiles small enough to fit on the EEPROM.

2023-11-16 02:38 UTC, lesshonor requested changes

2023-11-16 02:38 UTC, lesshonor commented on keyboards/inland/mk47/keymaps/vial/vial.json
> +    "keycodes": ["qmk_lighting"],
```suggestion
```
VIA V3 setting that does nothing in Vial.

2023-11-16 02:38 UTC, lesshonor commented on keyboards/inland/mk47/keymaps/vial/vial.json
> +    ],
```suggestion
```
VIA V3 settings that do nothing in Vial.

2023-11-16 03:11 UTC, usrfriendly commented on keyboards/inland/mk47/keymaps/vial/vial.json
> +    ],
Sorry, it was a little _too_ quick and dirty.  I made the edits, squashed the commits and pushed to keep things clean, and did a test-build/flash on my board where everything worked fine.

thanks @lesshonor

2023-11-16 16:06 UTC, lesshonor approved these changes

2023-11-16 16:06 UTC, lesshonor commented on keyboards/inland/mk47/keymaps/vial/vial.json
> +    "productId": "0x0002",
```suggestion
```
These technically aren't needed for Vial either, but doesn't really matter.

2023-11-18 05:35 UTC, adophoxia requested changes

2023-11-18 05:35 UTC, adophoxia commented on keyboards/inland/mk47/keymaps/vial/config.h
> +# pragma once
```suggestion
/* SPDX-License-Identifier: GPL-2.0-or-later */

# pragma once
```
Missing copyright header.

2023-11-19 05:29 UTC, usrfriendly commented
Tweaked to add licensing and clean up the unnecessary identifiers, did a test build on my end, and it's testing after push.

2023-11-21 20:42 UTC, lesshonor approved these changes

2023-11-22 03:19 UTC, adophoxia approved these changes

2023-11-22 03:45 UTC, merged