add Vault35 katana
vial-kb/vial-qmk pull request #605
Opened 2023-11-25 00:33 UTC by josh-l-wang

Adding Vault35 katana layout to Vial. Hopefully this will work as an individual PR.

2023-11-25 15:46 UTC, lesshonor requested changes

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/rgb.c
Ideally the information in this file would be migrated to `info.json` since it has no statements, only a definition...but just renaming it to `keyboards/jlw/vault35_katana/vault35_katana.c` will at least include it in all builds as a keyboard-level default because of how QMK is set up. (Go search through the repository; many, many keyboards [already use `keyboardname.c` for keyboard-level code](https://github.com/vial-kb/vial-qmk/blob/b1f7f46af8457907afa17aaf9f887ed43c679f92/keyboards/crkbd/crkbd.c).) So you don't have to manually include an extra `.c` file.

...BTW, the way to add additional source files is [to add `SRC += whatever.c` in a `rules.mk` file](https://docs.qmk.fm/#/config_options?id=build-options), [not to `#include` them](https://stackoverflow.com/questions/52792348/why-not-explicitly-include-c-files).

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/rgb.c
> +
```suggestion
#include "quantum.h"
```
`#ifdef` is not necessary and the LED index comment is incorrect.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/rgb.c
> +
```suggestion
```

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/keymaps/vial/keymap.c
> +#include "../../rgb.c"
```suggestion
```
This assumes the advice I provided earlier is taken.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/keymaps/vial/keymap.c
> +    [2] =   BLANK_LAYER
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] =   { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] =   { ENCODER_CCW_CW(_______, _______) },
    [2] =   { ENCODER_CCW_CW(_______, _______) }
```
There really isn't any need to overcomplicate this.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/keymaps/default/keymap.c
> +const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
```suggestion
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
```

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/keymaps/default/keymap.c
> +#include "../../rgb.c"
```suggestion
```

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/info.json
> +        {"pin_a": "A1", "pin_b": "A2", "resolution": 4}
```suggestion
        {"pin_a": "A1", "pin_b": "A2"}
```
`"resolution": 4` is the default, so there is no need to specify it here.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/config.h
> +#define DRIVER_LED_TOTAL RGB_MATRIX_LED_COUNT
```suggestion
#define RGB_MATRIX_LED_COUNT 12
```
Pin moved to `info.json`, rest is unnecessary

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/config.h
> +#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
```suggestion
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_DEFAULT_VAL 32
#define RGB_MATRIX_DEFAULT_SPD 32
```
Everything else is either a default setting or has been moved to `info.json`.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/rules.mk
> +RGB_MATRIX_DRIVER = ws2812
```suggestion
# This file intentionally left blank
```
All settings moved to `info.json`.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/keymaps/vial/rules.mk
> +VIALRGB_ENABLE = yes
```suggestion
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes
```
Ideally, encoder mapping goes in each keymap's `rules.mk`, not in the `config.h` for the entire keyboard.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/config.h
> +
```suggestion
```
See comment on the `vial` keymap re: encoder mapping. Don't forget to add a `keyboards/jlw/vault35_katana/keymaps/default/rules.mk` if you delete this.

2023-11-25 15:46 UTC, lesshonor commented on keyboards/jlw/vault35_katana/info.json
> +    },
```suggestion
        "bootmagic": true,
        "encoder": true,
        "extrakey": true,
        "mousekey": true,
        "nkro": true,
        "rgb_matrix": true
    },
    "rgb_matrix": {
        "animations": {
            "alphas_mods": true,
            "band_pinwheel_sat": true,
            "band_pinwheel_val": true,
            "band_sat": true,
            "band_spiral_sat": true,
            "band_spiral_val": true,
            "band_val": true,
            "breathing": true,
            "cycle_all": true,
            "cycle_left_right": true,
            "cycle_out_in": true,
            "cycle_out_in_dual": true,
            "cycle_pinwheel": true,
            "cycle_spiral": true,
            "cycle_up_down": true,
            "digital_rain": true,
            "dual_beacon": true,
            "gradient_left_right": true,
            "gradient_up_down": true,
            "hue_breathing": true,
            "hue_pendulum": true,
            "hue_wave": true,
            "jellybean_raindrops": true,
            "multisplash": true,
            "pixel_flow": true,
            "pixel_fractal": true,
            "pixel_rain": true,
            "rainbow_beacon": true,
            "rainbow_moving_chevron": true,
            "rainbow_pinwheels": true,
            "raindrops": true,
            "solid_multisplash": true,
            "solid_reactive": true,
            "solid_reactive_cross": true,
            "solid_reactive_multicross": true,
            "solid_reactive_multinexus": true,
            "solid_reactive_multiwide": true,
            "solid_reactive_nexus": true,
            "solid_reactive_simple": true,
            "solid_reactive_wide": true,
            "solid_splash": true,
            "splash": true,
            "typing_heatmap": true
        },
        "driver": "ws2812",
        "hue_steps": 4,
        "max_brightness": 69,
        "sat_steps": 4,
        "val_steps": 4
    },
    "ws2812": {
        "pin": "B15"
    },
```
1. `0,0` is the default matrix position for bootmagic, so you don't need to specify it.
2. Enabling `console` consumes an additional USB endpoint for no reason.
3. Moved most of the RGB Matrix settings to `info.json`, but you should note that some of these animations look pretty cruddy with only underglow LEDs or won't do anything (`alphas_mods` actually needs LEDs with the modifier flag set).
   You should probably actually test some of this.

2023-11-25 20:36 UTC, josh-l-wang reviewed
Thank you for your patience with this! Will keep all this in mind for the future.

2023-11-26 03:39 UTC, josh-l-wang commented
Apologies, I still need to integrate the rgb matrix data into info.json. Will re-request review when ready

2023-11-28 21:08 UTC, josh-l-wang commented
Okay I believe this is mostly corrected. Hopefully fully corrected. Much nicer to put everything possible into info.json.

2023-11-29 01:53 UTC, lesshonor requested changes
Way better, two small suggestions but that's it. 🎉

2023-11-29 01:53 UTC, lesshonor commented on keyboards/jlw/vault35_katana/config.h
> +
```suggestion
```
Since you transferred the LED layout over to `info.json`, QMK will count the number of LEDs for you—like the matrix row and col pins.

2023-11-29 01:53 UTC, lesshonor commented on keyboards/jlw/vault35_katana/config.h
> +#pragma once
```suggestion
/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once
```

2023-11-29 03:01 UTC, josh-l-wang reviewed
Thanks for all your help!

2023-11-29 08:41 UTC, lesshonor approved these changes

2023-12-03 05:28 UTC, merged