Adding VIAL support for GMMK Numpad
vial-kb/vial-qmk pull request #615
Opened 2023-12-04 16:07 UTC by ruohki

In order to get VIAL working on the GMMK Numpad i did:

- created a keymap.c for vial also enabling the encoder
- create a vial.json file
- added rules.mk
- modified the config.c to support vial

Nothing else has changed

2023-12-04 17:47 UTC, ruohki commented
Addition: This commit does not enable bluetooth

2023-12-05 15:14 UTC, lesshonor requested changes

2023-12-05 15:14 UTC, lesshonor commented on keyboards/gmmk/numpad/keymaps/vial/keymap.c
> +  ),
```suggestion
  )
```
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)

2023-12-05 15:14 UTC, lesshonor commented on keyboards/gmmk/numpad/keymaps/vial/keymap.c
> +    [3] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) }
```suggestion
    [1] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
```

2023-12-05 15:14 UTC, lesshonor commented on keyboards/gmmk/numpad/keymaps/vial/vial.json
> +    "productId": "0x5088",
```suggestion
```
Not used by Vial.

2023-12-05 15:14 UTC, lesshonor commented on keyboards/gmmk/numpad/config.h
> +
Move this into the `vial` keymap's `config.h`. If it is placed at the keyboard level it will eventually conflict with changes made upstream in QMK.

2023-12-07 11:00 UTC, ruohki commented on keyboards/gmmk/numpad/keymaps/vial/keymap.c
> +  ),
Aight, i just did what the docs said :) gonna put a change soon

2023-12-07 11:00 UTC, ruohki commented
thanks for the headsup gonna push some changes

2023-12-07 11:07 UTC, ruohki commented on keyboards/gmmk/numpad/keymaps/vial/vial.json
> +    "productId": "0x5088",
Does it really have to be removed? It is in for all the other gmmk keyboards

2023-12-08 11:49 UTC, lesshonor commented on keyboards/gmmk/numpad/keymaps/vial/vial.json
> +    "productId": "0x5088",
Not really; it takes up extra space, but this keyboard has external EEPROM so you aren't exactly constrained. It's in for all the other keyboards because they too cut-pasted the implementation, and didn't feel like bothering to remove it either.

2024-02-10 06:46 UTC, xyzz commented
Closing because there's been no update for over a month.

2024-02-10 06:46 UTC, closed without merging