add keyboards/handwired/dactyl_manuform/5x6_5
vial-kb/vial-qmk pull request #619
Opened 2023-12-08 15:10 UTC by shofel

2023-12-13 19:13 UTC, lesshonor requested changes

2023-12-13 19:13 UTC, lesshonor commented on keyboards/handwired/dactyl_manuform/5x6_5/keymaps/vial/vial.json
> +  "productId": "0x3536",
```suggestion
```
This is not used by Vial.

2023-12-15 15:10 UTC, shofel commented on keyboards/handwired/dactyl_manuform/5x6_5/keymaps/vial/vial.json
> +  "productId": "0x3536",
Accepted this. Thanks :)

2023-12-15 16:32 UTC, lesshonor approved these changes

2023-12-16 16:11 UTC, merged