Port Zed60 to VIAL
vial-kb/vial-qmk pull request #633
Opened 2023-12-26 05:53 UTC by austin4idps

In order to get VIAL working on the zed60 i did:

- created a keymap.c (same file from via)
- create a vial.json file (same file from via)
- added rules.mk
- added  config.c to support vial  

Nothing else has changed

2024-01-09 20:22 UTC, lesshonor requested changes

2024-01-09 20:22 UTC, lesshonor commented on keyboards/mechlovin/zed60/keymaps/vial/keymap.c
> +    ),
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
)
```

2024-01-09 20:43 UTC, lesshonor requested changes

2024-01-09 20:43 UTC, lesshonor commented on keyboards/mechlovin/zed60/keymaps/vial/vial.json
> +    ],
```suggestion
```
All of this is VIA/VIA V3 exclusive configuration which Vial does not use. Please review [the Vial documentation](https://get.vial.today/docs/lighting.html) and/or other keyboards in the Vial repository for how to implement lighting.

2024-02-15 04:35 UTC, xyzz commented
Closing because there's been no update for over a month.

2024-02-15 04:35 UTC, closed without merging