Add Vial support for cannonkeys/moment_hs
vial-kb/vial-qmk pull request #634
Opened 2023-12-29 23:05 UTC by marcelmaltry

I added Vial support for `cannonkeys/moment_hs`.

2024-01-09 20:41 UTC, lesshonor requested changes

2024-01-09 20:41 UTC, lesshonor commented on keyboards/cannonkeys/moment_hs/keymaps/vial/keymap.c
> +        _______, _______, _______,                            _______,                                     _______, _______, _______
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
```

2024-01-09 20:41 UTC, lesshonor commented on keyboards/cannonkeys/moment_hs/keymaps/vial/vial.json
> +  "productId": "0x0013",
```suggestion
```
These attributes are not used by Vial.

2024-01-10 09:44 UTC, marcelmaltry commented on keyboards/cannonkeys/moment_hs/keymaps/vial/keymap.c
> +        _______, _______, _______,                            _______,                                     _______, _______, _______
Thanks, didn't know that!

2024-01-10 11:56 UTC, lesshonor approved these changes

2024-01-21 18:52 UTC, merged