Add keyboard: takayoshiotake/five_octave
vial-kb/vial-qmk pull request #639
Opened 2024-01-03 13:20 UTC by takayoshiotake

Add keyboard takayoshiotake/five_octave

2024-01-08 06:42 UTC, takayoshiotake commented
I also added a default keymap.

2024-01-09 20:47 UTC, lesshonor requested changes

2024-01-09 20:47 UTC, lesshonor commented on keyboards/takayoshiotake/five_octave/keymaps/vial/vial.json
> +    "productId": "0x8CAE",
```suggestion
```
These attributes are not used by Vial.

2024-01-09 20:47 UTC, lesshonor commented on keyboards/takayoshiotake/five_octave/info.json
> +        "console": false,
These settings are not enabled by default, so there is no need to explicitly disable them here.
```suggestion
```

2024-01-09 20:47 UTC, lesshonor commented on keyboards/takayoshiotake/five_octave/keymaps/default/keymap.c
> +	),
No need to hardcode filler `KC_TRNS` layers. For non-dynamic keymaps it's pointless, and dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
    )
```

2024-01-09 20:47 UTC, lesshonor commented on keyboards/takayoshiotake/five_octave/keymaps/vial/keymap.c
> +	),
```suggestion
)
```
Please see previous comment about extra blank layers.

2024-01-10 14:25 UTC, takayoshiotake commented
Thank you for your response. I applied the suggestions and cleaned up the code.

2024-01-10 14:39 UTC, lesshonor approved these changes

2024-01-21 18:53 UTC, merged