Bruce the keyboard
vial-kb/vial-qmk pull request #647
Opened 2024-01-09 23:14 UTC by josh-l-wang

adding bruce the keyboard

2024-01-11 01:09 UTC, lesshonor commented
[Previously...](https://github.com/vial-kb/vial-qmk/pull/595#pullrequestreview-1722085946)

My suggestion to you is to quit using [your copy of the `vial` branch](https://github.com/josh-l-wang/vial-qmk/tree/vial). Rename or delete it if you have to. Assuming your `upstream` is `vial-kb/vial-qmk`, when you start adding a new keyboard, run:
- `git fetch upstream`
- `git checkout -b new_branch_name upstream/vial`

2024-01-12 02:39 UTC, lesshonor requested changes

2024-01-12 02:39 UTC, lesshonor commented on keyboards/jlw/bruce_the_keyboard/config.h
You can delete this file, since it's not doing anything.

2024-01-12 02:39 UTC, lesshonor commented on keyboards/jlw/vault35_katana/rgb.c
Please delete this file.

2024-01-12 02:39 UTC, lesshonor commented on keyboards/jlw/bruce_the_keyboard/keymaps/vial/config.h
> +
Not a huge deal, but technically this isn't necessary as it is default.
```suggestion
```

2024-02-15 04:35 UTC, xyzz commented
Closing because there's been no update for over a month.

2024-02-15 04:35 UTC, closed without merging