flehrad/bigswitch: adding Vial port, expand flash documentation
vial-kb/vial-qmk pull request #649
Opened 2024-01-15 17:59 UTC by edgriebel

* Adding a Vial port for Bigswitch. No changes to keymaps etc. other than required for Vial.
* Added more detailed description of how to flash Pro Micro as it's a problem I ran into while porting this. It's probably obvious for people experienced building keyboards, but as a first-time builder this info would have saved me a lot of time.

2024-01-21 00:26 UTC, lesshonor requested changes

2024-01-21 00:26 UTC, lesshonor commented on keyboards/flehrad/bigswitch/readme.md
Please revert the changes to this file. If you genuinely feel more elaboration on how to flash a Pro Micro is necessary in this specific readme (there are kind of [a](https://docs.keeb.io/flashing-firmware) [lot](https://kriscables.com/flash-controller-qmk/) [of](https://airton.dev/til/qmk-how-to-flash-arduino-pro-micro-or-elite-c/) [places](https://mechwild.com/guides/general/flashing-a-pro-micro/) [with](https://www.youtube.com/watch?v=GwqlT5Xy4Ng) [instructions](https://docs.qmk.fm/#/flashing?id=caterina) [already](https://pabileonline.blogspot.com/2020/09/how-to-flash-qmk-firmware.html)) ...please consider submitting this change [upstream](https://github.com/qmk/qmk_firmware/pulls).

2024-01-21 00:26 UTC, lesshonor commented on keyboards/flehrad/bigswitch/keymaps/vial/config.h
> +#define VIAL_UNLOCK_COMBO_COLS { 1, 1 }
While it would arguably go against the spirit of the thing on a keyboard with multiple keys—you can have an unlock combination that is a single key.
```suggestion
#define VIAL_UNLOCK_COMBO_ROWS { 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0 }
```

2024-01-21 00:26 UTC, lesshonor commented on keyboards/flehrad/bigswitch/keymaps/vial/rules.mk
> +
```suggestion
```

2024-01-21 00:46 UTC, lesshonor requested changes

2024-01-21 00:46 UTC, lesshonor commented on keyboards/flehrad/bigswitch/keymaps/vial/keymap.c
> +#define SLEEP_OSX LALT(LGUI(KC_OSX_EJECT))
```suggestion
#define LOCK_OSX LSFT(LCTL(KC_KB_POWER))
#define SLEEP_OSX LALT(LGUI(KC_KB_POWER))
```
This keycode is already defined:
https://github.com/vial-kb/vial-qmk/blob/b4cfa21cb6bb2b6490268b323eaae8fbc2a19707/quantum/keycodes.h#L193

2024-01-27 01:25 UTC, edgriebel commented on keyboards/flehrad/bigswitch/readme.md
Makes sense, content reverted.

2024-01-27 23:20 UTC, lesshonor approved these changes

2024-01-29 01:36 UTC, merged