more or less default vial implementation for the treadstone48
vial-kb/vial-qmk pull request #652
Opened 2024-01-19 17:34 UTC by devilzmods

I did this a while ago, so i hope past me put everything in order.

2024-01-20 23:51 UTC, lesshonor requested changes
[This does not build](https://github.com/vial-kb/vial-qmk/actions/runs/7587210358).

2024-01-20 23:51 UTC, lesshonor commented on keyboards/marksard/treadstone48/rev1/keymaps/dvz/config.h
Please delete this keymap folder.

https://github.com/vial-kb/vial-qmk/blob/b4cfa21cb6bb2b6490268b323eaae8fbc2a19707/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L7

2024-01-20 23:51 UTC, lesshonor commented on keyboards/marksard/treadstone48/keymaps/vial/readme.md
Please delete this file. It doesn't add any useful information (...and this isn't the default keymap)

2024-01-20 23:51 UTC, lesshonor commented on keyboards/marksard/treadstone48/keymaps/vial/config.h
> +
```suggestion
```
Given mousekeys had to be disabled by default anyway, I don't see much need for all these presets. The commented out macros don't do anything either.

2024-01-20 23:51 UTC, lesshonor commented on keyboards/marksard/treadstone48/keymaps/vial/readme_jp.md
This one should probably be deleted too. While it might contain some useful information, some things are incorrect (the `tmk_core/common` folder no longer even exists).
It's still ultimately just a copy of https://github.com/vial-kb/vial-qmk/blob/vial/keyboards/marksard/treadstone48/keymaps/default/readme_jp.md and if someone wants to read it they can go read it there.

2024-01-21 12:40 UTC, devilzmods reviewed
deleted my personal keymap and removed readmes

2024-02-15 04:38 UTC, xyzz commented
- the readme file is useless (empty) and should be removed
- the build is failing on CI please fix it

2024-04-27 08:11 UTC, xyzz commented
Closing as no updates over a month

2024-04-27 08:11 UTC, closed without merging