Add keyboard: KMAC Happy & Porting to Vial.
vial-kb/vial-qmk pull request #670
Opened 2024-02-13 06:27 UTC by nlnjnj

* Add keyboard: KBDMOD KMAC Happy
* Porting KBDMOD KMAC Happy to Vial

2024-02-17 10:23 UTC, nlnjnj commented
Updated:
* Add Vial support for keyboard: JER J80

2024-02-26 12:58 UTC, lesshonor requested changes
...I'm not even touching the custom matrix stuff. GLWT, and don't forget that you are ultimately responsible for continued maintenance of your keyboards post-submission.

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/info.json
Please revert changes to this file. It will cause conflicts when updates are merged into Vial from upstream QMK. If you want to make global changes to this keyboard, [open a pull request against the QMK repository](https://github.com/qmk/qmk_firmware/pulls).

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/default/keymap.c
Please revert changes to this file.

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/default_iso/keymap.c
Please revert changes to this file.

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/vial/rules.mk
> +VIAL_INSECURE   = no
This is the default.
```suggestion
```

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/vial/config.h
> +#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }
```suggestion
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/vial/keymap.c
> +
```suggestion
```

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/vial/keymap.c
> +  KC_TRNS, KC_TRNS, KC_TRNS,                            KC_TRNS,                            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum configured. Given this keyboard's limited memory, conserving space is a better idea than pre-allocating a layer with one useful key.
```suggestion
  KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_APP, KC_RALT, KC_RGUI, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT)
```

2024-02-26 12:58 UTC, lesshonor commented on keyboards/j80/keymaps/vial/keymap.c
> +}
```suggestion
```

2024-02-26 12:58 UTC, lesshonor commented on keyboards/kmac_happy/keymaps/vial/keymap.c
> +    KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS,                                     KC_TRNS, KC_TRNS, KC_TRNS
```suggestion
```

2024-02-28 12:48 UTC, lesshonor requested changes

2024-02-28 12:48 UTC, lesshonor commented on keyboards/j80/readme.md
Somehow I missed this. Revert the changes to this file too—or better yet, [fix the typos for everyone](https://github.com/qmk/qmk_firmware/pulls).

2024-02-28 12:48 UTC, lesshonor commented on keyboards/j80/rules.mk
Revert the changes to this file too. If you want mousekeys in the Vial keymap (...and they actually fit on an atmega32a...) you could always put them in there.

2024-03-11 08:54 UTC, nlnjnj commented on keyboards/j80/rules.mk
Could you provide any documents or links for how to enable mousekeys as default option? I do not understand this suggestion actually.

2024-03-11 13:40 UTC, lesshonor commented on keyboards/j80/rules.mk
Add `MOUSEKEY_ENABLE = yes` to `keyboards/j80/keymaps/vial/rules.mk`.
If you want to add `MOUSEKEY_ENABLE = yes` to `keyboards/j80/rules.mk`, [open a pull request in the QMK repository](https://github.com/qmk/qmk_firmware/pulls).

2024-03-12 01:48 UTC, nlnjnj commented on keyboards/j80/rules.mk
Thanks

2024-04-27 22:53 UTC, merged