Adding Krado66 Keyboard
vial-kb/vial-qmk pull request #672
Opened 2024-02-15 04:32 UTC by Feags

Adding Krado Industries keyboard Krado66 vial keymap and supporting files.

The Krado66 is already in the QMK repo with VIA keymaps. This PR adds /vial folder with config.h keymap.c rules.mk and vial.json.

2024-02-15 16:07 UTC, lesshonor requested changes

2024-02-15 16:07 UTC, lesshonor commented on keyboards/kradoindustries/krado66/keymaps/vial/config.h
> +#define VIAL_ENCODER_DEFAULT { KC_PGDN, KC_PGUP, KC_PGDN, KC_PGUP, KC_VOLD, KC_VOLU, RGB_MOD, RGB_RMOD, KC_PGDN, KC_PGUP, KC_PGDN, KC_PGUP, KC_VOLD, KC_VOLU, KC_LEFT, KC_RGHT, KC_LBRC,  KC_RBRC, KC_L
Obsolete and redundant settings removed.
```suggestion
#define VIALRGB_NO_DIRECT

#define DYNAMIC_KEYMAP_MACRO_COUNT 6
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

2024-02-15 16:07 UTC, lesshonor commented on keyboards/kradoindustries/krado66/keymaps/vial/rules.mk
> +MOUSEKEY_ENABLE = no
Obsolete and redundant rules removed.
```suggestion
COMBO_ENABLE = no
QMK_SETTINGS = yes
ENCODER_MAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
MOUSEKEY_ENABLE = no
```

2024-02-15 16:07 UTC, lesshonor commented on keyboards/kradoindustries/krado66/keymaps/vial/vial.json
> +  ],
Attributes not used by Vial removed.
```suggestion
  "lighting": "qmk_rgblight",
```

2024-02-16 01:47 UTC, Feags commented
@lesshonor Suggestions committed.

2024-02-18 00:32 UTC, merged