Add vial support to bm43a
vial-kb/vial-qmk pull request #677
Opened 2024-02-17 03:26 UTC by thiromi

Got a bm43a and what a frustation it was by it not being vial compatible!

After looking into [this video](https://youtu.be/O8pdUPqPG3k?si=ZaNv717vai9nXfRz) explaining how easy it was to add vial support, I decided to give it a try and add the support myself and looks like I was successful doing it.

Had to disable combos and key overrides in order to be able to flash the firmware, otherwise the file size would be too big.

Tested the keys in the Matrix tester and everything seems to be working

<img width="879" alt="Screenshot 2024-02-17 at 04 25 43" src="https://github.com/vial-kb/vial-qmk/assets/83295/305528b0-6e70-4e49-8a1d-e579c0e77fa8">

2024-02-18 01:16 UTC, xyzz requested changes

2024-02-18 01:16 UTC, xyzz commented on keyboards/kprepublic/bm43a/keymaps/vial/readme.md
> +# The default keymap for bm43a
Remove this file

2024-02-18 13:55 UTC, thiromi commented on keyboards/kprepublic/bm43a/keymaps/vial/readme.md
> +# The default keymap for bm43a
Done

2024-03-01 17:41 UTC, thiromi commented
@xyzz when you have the time to review this pr again 🙏

2024-03-10 22:12 UTC, merged