Add Brian the Keyboard
vial-kb/vial-qmk pull request #682
Opened 2024-02-26 00:29 UTC by NCKiser

2024-02-26 16:30 UTC, lesshonor requested changes

2024-02-26 16:30 UTC, lesshonor commented on keyboards/jlw/brian_the_keyboard/keymaps/default/keymap.c
> +                   _______,            _______,  _______,  _______,  _______,            _______
No need to hardcode filler `KC_TRNS` layers. For non-dynamic keymaps it's pointless, and dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`.

...also don't forget to compile your keymaps before opening a pull request.
```suggestion
                 KC_LCTRL,       MO(1),  KC_ENT, KC_SPC, MO(2),          KC_RALT
```

2024-02-26 16:30 UTC, lesshonor commented on keyboards/jlw/brian_the_keyboard/keymaps/vial/keymap.c
> +                   _______,            _______,  _______,  _______,  _______,            _______
See previous suggestion.
```suggestion
```

2024-02-27 14:29 UTC, NCKiser commented on keyboards/jlw/brian_the_keyboard/keymaps/vial/keymap.c
> +                   _______,            _______,  _______,  _______,  _______,            _______
Removed trans layers with recent commit

2024-02-27 14:29 UTC, NCKiser commented on keyboards/jlw/brian_the_keyboard/keymaps/default/keymap.c
> +                   _______,            _______,  _______,  _______,  _______,            _______
Absolutely correct, thank you for bringing that to my attention. This has been resolved in the most recent commit

2024-02-28 01:26 UTC, lesshonor approved these changes

2024-03-10 22:13 UTC, merged