Added support of OLKB Preonic
vial-kb/vial-qmk pull request #740
Opened 2024-05-25 13:45 UTC by alderaan-rock

Hello, 
 
I copied the default keymap and removed two layers (COLEMAK & DVORAK), as they were preventing the firmware from compiling and were not necessary.

Have a nice day !

2024-05-25 21:11 UTC, lesshonor requested changes
Which revision of the Preonic is this for?
They aren't all wired the same way, so they can't have a single Vial keymap. You'll need to move this under whatever revision folder you tested it with.

2024-05-25 21:11 UTC, lesshonor commented on keyboards/preonic/keymaps/vial/readme.md
I'd delete this file; it doesn't really add anything.

2024-05-26 07:27 UTC, alderaan-rock commented on keyboards/preonic/keymaps/vial/readme.md
I deleted the file as suggested

2024-05-26 07:29 UTC, alderaan-rock commented
Hi,

I moved the Vial keymap to preonic/rev3_drop/keymaps/vial 

Regards,

2024-06-23 06:51 UTC, merged