Vial keymap for GMMK V2 96 ISO
vial-kb/vial-qmk pull request #747
Opened 2024-06-09 21:29 UTC by nobwyn

Converted existing VIA keymap to VIAL compatible keymap for Glorious GMMK V2 96 ISO

2024-06-18 19:17 UTC, adophoxia requested changes

2024-06-18 19:17 UTC, adophoxia commented on keyboards/gmmk/gmmk2/p96/iso/keymaps/vial/rules.mk
> +LTO_ENABLE = yes
Is there a reason this needs to be added? Doubt this would help considering the MCU used on this board has enough flash space already.

2024-06-18 19:17 UTC, adophoxia commented on keyboards/gmmk/gmmk2/p96/iso/keymaps/vial/vial.json
> +  ],
Since you have `VIALRGB_ENABLE = yes` in the `vial` keymap's `rules.mk`, this should really be changed to 
```suggestion
"lighting": "vialrgb",
```

2024-06-18 19:17 UTC, adophoxia commented on keyboards/gmmk/gmmk2/p96/iso/keymaps/vial/config.h
> +#define RGB_MATRIX_KEYPRESSES
Not needed since just having the effects associated with this `#define` in `info.json` enabled is already enough.
```suggestion

```

2024-06-22 16:16 UTC, nobwyn commented on keyboards/gmmk/gmmk2/p96/iso/keymaps/vial/rules.mk
> +LTO_ENABLE = yes
I took it 1:1 over from the ANSI layout. Now it's disabled, as it seems to be not needed...

2024-06-23 06:52 UTC, merged