Added vial support for For_Science
vial-kb/vial-qmk pull request #769
Opened 2024-08-12 15:56 UTC by arko9699

2024-08-26 08:09 UTC, xyzz requested changes

2024-08-26 08:09 UTC, xyzz commented on keyboards/for_science/keyboard.json
> -        "command": true,
do not modify files outside of the vial keymap that also exist in upstream qmk, this will cause conflicts during merge

2024-09-02 02:42 UTC, xyzz commented
there are still modifications outside of the vial keymap

2024-09-02 15:25 UTC, arko9699 commented
I'm sorry for the frankly egregious series of errors I've made. It should hopefully be correct now.

2024-09-07 21:12 UTC, merged