Add VIAL support for tofu65v2/tofu_jr
vial-kb/vial-qmk pull request #776
Opened 2024-08-24 00:36 UTC by Blood13

After that the VIA stops to work. You can use tofu_jr.json from kbdfans official store. VIA repository needs a json v2 PR for  support of the keyboard.

2024-08-24 11:42 UTC, strikestr approved these changes

2024-08-26 08:10 UTC, xyzz commented
fails to build

2024-08-26 08:15 UTC, Blood13 commented
Ok, I'll try to fix it today.

2024-09-02 00:55 UTC, adophoxia requested changes

2024-09-02 00:55 UTC, adophoxia commented on keyboards/dztech/tofu/jr/v1/keymaps/vial/vial.json
> +  ],
```suggestion
  "keycodes": [
    "qmk_lighting"
  ],
  "menus": [
    "qmk_rgb_matrix"
  ],
```
Vial does not recognize these objects, so they can just be deleted.

2024-09-07 20:21 UTC, merged