Lefty candybar firmware - does not work
vial-kb/vial-qmk pull request #779
Opened 2024-08-30 15:37 UTC by niclake

;

2024-09-15 03:49 UTC, lesshonor requested changes

2024-09-15 03:49 UTC, lesshonor commented on keyboards/tkc/candybar/lefty/keymaps/vial/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
```

2024-09-15 03:49 UTC, lesshonor commented on keyboards/tkc/candybar/lefty/keymaps/vial/vial.json
> +  "firmwareVersion": 0,
```suggestion
  "matrix": {
      "rows": 4,
      "cols": 17
  },
```
The other attributes are not used by Vial.

2024-10-27 06:12 UTC, xyzz commented
there is no update for over a month, closing

2024-10-27 06:12 UTC, closed without merging