Added Vial support for Quark, pi60 HSE, and TKC m0lly
vial-kb/vial-qmk pull request #821
Opened 2024-11-30 03:23 UTC by seirin-blu

Added vial support for Checkerboars Quark, 1upkeyboards pi60 HSE, and TKC m0lly. All three of these compile and are running on their respective keyboards that I have in my possession.

2024-11-30 03:24 UTC, xyzz requested changes

2024-11-30 03:24 UTC, xyzz commented on keyboards/tkc/m0lly/rules.mk
> +COMBO_ENABLE = yes
Do not modify files outside of the vial keymap directory

2024-11-30 03:24 UTC, xyzz commented on keyboards/checkerboards/quark/Quark VIAL files.zip
Remove this file

2024-11-30 03:24 UTC, xyzz commented on keyboards/1upkeyboards/pi60_hse/keymaps/vial/rules.mk
> +VIAL_INSECURE = no
Remove this

2024-11-30 03:24 UTC, xyzz commented on keyboards/checkerboards/quark/keymaps/vial_4x12/rules.mk
> +VIAL_INSECURE = no
Remove this

2024-12-04 14:57 UTC, lesshonor requested changes

2024-12-04 14:57 UTC, lesshonor commented on keyboards/1upkeyboards/pi60_hse/keymaps/vial/keymap.c
> +        KC_TRNS, KC_TRNS, KC_TRNS,                         KC_TRNS,                               KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`.
```suggestion
```

2024-12-04 14:57 UTC, lesshonor commented on keyboards/checkerboards/quark/keymaps/vial_4x12/config.h
Please rename this keymap `vial` [so it will be detected and built by CI](https://github.com/vial-kb/vial-qmk/actions/runs/12093146265/job/33723794210#step:4:92). [There's a line in the PR template about this.](https://github.com/vial-kb/vial-qmk/blob/d2e952ee92b58fe6a6ea571e137e6fc33e1fead4/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L7)

2024-12-04 21:16 UTC, seirin-blu commented
I'll (hopefully) make all of the required changes tonight. IDK what I was thinking when I submitted this bc I missed a lot of little stuff lmao

2025-01-02 02:11 UTC, closed without merging