feat: add VIAL support for xt60_singa
vial-kb/vial-qmk pull request #824
Opened 2024-12-03 20:50 UTC by Blood13

So, the firmware for the xt60_singa is ready.
- Support for both VIA and VIAL (except for the Key Override function due to the image size limitations).
- Fixed a bug with the inverted CapsLock, relevant for white hot-swap boards. When CapsLock was pressed (LED lit up), lowercase letters were typed, and vice versa: when it was off, uppercase letters were typed. Essentially, the CapsLock LED was always on in its normal state, which was extremely annoying.

2024-12-14 19:45 UTC, lesshonor requested changes
If this was an ARM board these would just be nitpicks, but atmega32u4 (especially with RGB enabled) needs all the help it can get to keep filesize down.

2024-12-14 19:45 UTC, lesshonor commented on keyboards/kopibeng/xt60_singa/keymaps/vial/keymap.c
> +
No need to hardcode filler `KC_TRNS` layers. Dynamic keymaps will automatically fill in "missing" layers at compile-time up to the maximum set in `dynamic_keymap.layer_count`. (By default, this is 4.)
```suggestion
    )
};
```

2024-12-14 19:45 UTC, lesshonor commented on keyboards/kopibeng/xt60_singa/keymaps/vial/vial.json
> +    "productId": "0x0601",
```suggestion
```
These attributes are not used by Vial.

2025-01-25 22:22 UTC, merged

2025-01-25 23:13 UTC, Blood13 commented
I've missed the discussion. It's allright, thank you.