fixed
vial-kb/vial-qmk pull request #93
Opened 2021-12-12 20:35 UTC by ll3macorn

i fixed this (hopefully)

2021-12-12 20:44 UTC, xyzz requested changes

2021-12-12 20:44 UTC, xyzz commented on keyboards/ll3macorn/bongopad/config.h
> +#define DYNAMIC_KEYMAP_LAYER_COUNT 4
this should go into `keymaps/vial/config.h`

2021-12-22 04:39 UTC, xyzz commented
Not sure you saw, but the ci build fails:

```
2021-12-13T11:26:41.3921234Z [01m[Kkeyboards/ll3macorn/bongopad/keymaps/vial/keymap.c:168:6:[m[K [01;31m[Kerror: [m[Kconflicting types for ‘[01m[Koled_task_user[m[K’
```

2021-12-22 05:04 UTC, ll3macorn commented
> Not sure you saw, but the ci build fails:
> 
> ```
> 2021-12-13T11:26:41.3921234Z �[01m�[Kkeyboards/ll3macorn/bongopad/keymaps/vial/keymap.c:168:6:�[m�[K �[01;31m�[Kerror: �[m�[Kconflicting types for ‘�[01m�[Koled_task_user�[m�[K’
> ```

ive been a bit busy lately thats why. i just attempted to build the exact code on my computer and it works so

2022-09-21 06:02 UTC, closed without merging